### PR TITLE
Simplify and unify error handling

### LINKED ISSUE #10541: Catch BGS transient errors
We already catch some of the transient errors but in different context (see https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/exceptions/bgs_sync_error.rb)
We should catch it and make them transient.  
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4751/
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3936/
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4052/

### PR DESCRIPTION
**Pull request by monfresh**
**Why**: In order to make it easier to handle errors from VBMS and BGS,
we moved the logic to those gems which now provide a handy `transient?`
method we can use to determine whether or not to send the error to
Sentry.

By adding `rescue_from` clauses in `ApplicationJob` and the parent
controllers, we ensure all transient errors can be caught.

There are likely still cases where we rescue from VBMS and BGS errors
directly in other files, but to keep this PR as small as possible, those
can be addressed later if we find we are still seeing transient errors
in Sentry.

Resolves #10541

Depends on these other PRs:
https://github.com/department-of-veterans-affairs/connect_vbms/pull/227
https://github.com/department-of-veterans-affairs/ruby-bgs/pull/80

### CODE REVIEW

File: app/jobs/decision_issue_sync_job.rb [hunk 1]
```diff
@@ -11,15 +11,12 @@ def perform(request_issue_or_effectuation)
...
       request_issue_or_effectuation.sync_decision_issues!
-    rescue Rating::NilRatingProfileListError, Rating::LockedRatingError, Rating::BackfilledRatingError => error
-      request_issue_or_effectuation.update_error!(error.class.to_s)
-      # no Raven report, just noise. This just means nothing new has happened.
     rescue Errno::ETIMEDOUT => error
-      Rails.logger.error error
       # no Raven report. We'll try again later.
+      Rails.logger.error error
     rescue StandardError => error
-      request_issue_or_effectuation.update_error!(error.to_s)
```
Comment (pkarman) [inline app/jobs/decision_issue_sync_job.rb]: the `to_s` vs `inspect` method is subtly different iirc. I think we were using `to_s` because we want the error string to always be prefixed by the class name so that it is easier to read on the /jobs page and in reports.

File: app/models/rating.rb [hunk 2]
```diff
@@ -3,9 +3,23 @@
 class Rating
   include ActiveModel::Model
 
-  class NilRatingProfileListError < StandardError; end
-  class LockedRatingError < StandardError; end
-  class BackfilledRatingError < StandardError; end
+  class NilRatingProfileListError < StandardError
+    def transient?
```
Comment (pkarman) [inline app/models/rating.rb]: I understand why we're calling these 'transient' in order to keep them from sentry, but they aren't really transient in the sense that they are due to unknown upstream service errors. They are due to data integrity issues and should eventually resolve themselves and which we don't need to worry ourselves unnecessarily.

Could we either comment to that effect or somehow indicate that these are not transient in the same sense that unknown HTTP/network errors are?

File: app/services/vbms_request.rb [hunk 3]
```diff
@@ -0,0 +1,25 @@
+# frozen_string_literal: true
```
Comment (pkarman) [inline app/services/vbms_request.rb]: I think we're trying to keep these in the `external_api` namespace.

File: app/jobs/decision_issue_sync_job.rb (hunk 1 above)
Comment (monfresh) [reply app/jobs/decision_issue_sync_job.rb]: In other places, we are using `inspect`, so I thought I'd make it consistent, and also simplify the code. Before, the string displayed was different depending on the type of error. If it was a `Rating` error, it would only display the class name, such as `Rating::NilRatingProfileListError`. If it was a `StandardError`, it would only display the error message.

Now, the `decision_sync_error` is consistent for all error types. It displays both the class name and the error message, such as `#<Rating::NilRatingProfileListError: error message>` and `#<StandardError: error message>`. See the corresponding spec for the diff.

File: app/models/rating.rb (hunk 2 above)
Comment (monfresh) [reply app/models/rating.rb]: Yes, we can. How about a more generic `ignorable?` that can apply to all types of errors we want to ignore, whether transient or not? I think our main goal here is to identify errors we don't care about, whether they are transient or some other type of error we don't want to send to Sentry, right?

File: app/services/vbms_request.rb (hunk 3 above)
Comment (monfresh) [reply app/services/vbms_request.rb]: Fixed here: https://github.com/department-of-veterans-affairs/caseflow/pull/11418/commits/62811953249c090321acce2954768ee53b10445a

**Comment by monfresh** [comment]
@pkarman Thoughts on my comments?

File: app/models/rating.rb (hunk 2 above)
Comment (pkarman) [reply app/models/rating.rb]: Yes `.ignorable?` seems good.

File: app/jobs/decision_issue_sync_job.rb (hunk 1 above)
Comment (pkarman) [reply app/jobs/decision_issue_sync_job.rb]: As long as we're consistent with #11093 then I'm cool.

**Comment by pkarman** [comment]
@monfresh let me know if I missed anything and if this is ready for a final 👍 -- I think the `.ignorable?` was just at the proposal phase yes?

**Comment by monfresh** [comment]
I think this is ready for final 👍. I updated `transient?` to `ignorable?` in this PR, and opened 2 new PRs in `ruby-bgs` and `connect_vbms`. Once those PRs are merged, I will update this PR to point the Gemfile to the latest `ref`.

File: app/jobs/task_timer_job.rb [hunk 4]
```diff
@@ -43,7 +45,7 @@ def process(task_timer)
     # Ensure errors are sent to Sentry, but don't block the job from continuing.
     # The next time the job runs, we'll process the unprocessed task timers again.
     task_timer.update_error!(error.inspect)
-    Raven.capture_exception(error)
+    capture_exception(error: error)
```
Comment (lowellrex) [inline app/jobs/task_timer_job.rb]: Why are we removing the namespace prefix here?

Comment (monfresh) [reply app/jobs/task_timer_job.rb]: This is a method defined in `ApplicationJob` that handles errors for all jobs so that we can ignore certain errors. See `app/jobs/application_job` above.
