### PR TITLE
Shalliburton/13208 fix disposition undefined

### LINKED ISSUE #13208: Cannot read property 'disposition' of undefined
Sentry Alerts
[Here](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7869/?query=is%3Aunresolved%20%22Cannot%20read%20property%20%27disposition%27%20of%20undefined%22)
[Here](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6352/?query=is%3Aunresolved%20%22Cannot%20read%20property%20%27disposition%27%20of%20undefined%22)
[Here](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5299/?query=is%3Aunresolved%20%22Cannot%20read%20property%20%27disposition%27%20of%20undefined%22)
[Here](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5117/?query=is%3Aunresolved%20%22Cannot%20read%20property%20%27disposition%27%20of%20undefined%22)
[Here](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4471/?query=is%3Aunresolved%20%22Cannot%20read%20property%20%27disposition%27%20of%20undefined%22)

Seems to occur both when the [hearing has been deleted in vacols](https://dsva.slack.com/archives/CLRTL92TW/p1579640832010700?thread_ts=1579620081.004800&cid=CLRTL92TW) or the [hearing association on a hearing task does not exist](https://dsva.slack.com/archives/CHX8FMP28/p1575556723017300).

### PR DESCRIPTION
**Pull request by sahalliburton**
Resolves #13208 

### Description
Added error handling to prevent modal from crashing and catch error when hearing or hearing task association is missing

### Acceptance Criteria
- [ ] Code compiles correctly
- [ ] User can change hearing disposition

### Testing Plan
1. Select judge "BVATWARNER": http://localhost:3000/test/users
1. Navigate to queue:  http://localhost:3000/queue
1. Change view to the admin teams view
1. Select one of the cases with the task set to "Change Hearing Disposition"
1. Change the hearing disposition and ensure you do not receive an error

### CODE REVIEW

File: app/models/tasks/assign_hearing_disposition_task.rb [hunk 1]
```diff
@@ -138,13 +138,29 @@ def update_hearing_and_self(params:, payload_values:)
...
     if hearing.is_a?(LegacyHearing)
       hearing.update_caseflow_and_vacols(disposition: disposition)
     else
       hearing.update(disposition: disposition)
     end
   end
 
+  def check_hearing_exists(hearing)
+    # Ensure the hearing exists
+    if hearing.nil? && hearing.is_a?(LegacyHearing)
```
Comment (ferristseng) [inline app/models/tasks/assign_hearing_disposition_task.rb:157]: Is this top conditional possible?

File: app/models/tasks/assign_hearing_disposition_task.rb [hunk 2]
```diff
@@ -138,13 +138,29 @@ def update_hearing_and_self(params:, payload_values:)
...
+      fail Caseflow::Error::VacolsRecordNotFound => error
```
Comment (ferristseng) [inline app/models/tasks/assign_hearing_disposition_task.rb:158]: Do you need the `=> error` part of this? Is this valid syntax?

File: client/app/queue/ChangeHearingDispositionModal.jsx [hunk 3]
```diff
@@ -73,64 +67,68 @@ class ChangeHearingDispositionModal extends React.Component {
...
+    const { appeal, highlightFormItems, task } = this.props;
 
     const hearing = _.find(appeal.hearings, { externalId: task.externalHearingId });
-    const currentDisposition = hearing.disposition ? _.startCase(hearing.disposition) : 'None';
-    const dispositionOptions = Object.keys(HEARING_DISPOSITION_TYPES).map((key) =>
-      ({
-        value: key,
-        label: _.startCase(key)
-      })
+    const currentDisposition = hearing?.disposition ? _.startCase(hearing?.disposition) : 'None';
```
Comment (ferristseng) [inline client/app/queue/ChangeHearingDispositionModal.jsx:88]: In `_.startCase(hearing?.disposition)`, I think that doesn't need the safe navigation since you're checking beforehand.

File: app/controllers/tasks_controller.rb [hunk 4]
```diff
@@ -97,6 +97,10 @@ def update
     tasks_to_return = (QueueForRole.new(user_role).create(user: current_user).tasks + tasks).uniq
 
     render json: { tasks: json_tasks(tasks_to_return) }
+  rescue ActiveRecord::RecordInvalid => error
+    Raven.capture_exception(error)
```
Comment (ferristseng) [inline app/controllers/tasks_controller.rb:101]: Do we need to re-raise the error here / render something here?

File: app/models/tasks/assign_hearing_disposition_task.rb (hunk 1 above)
Comment (sahalliburton) [reply app/models/tasks/assign_hearing_disposition_task.rb]: just realized that and removed, my apologies

File: app/models/tasks/assign_hearing_disposition_task.rb [hunk 5]
```diff
@@ -138,13 +138,27 @@ def update_hearing_and_self(params:, payload_values:)
   end
 
   def update_hearing_disposition(disposition:)
+    check_hearing_exists(hearing)
+
+    # Ensure the hearing task association exists
+    if hearing_task.hearing_task_association.nil?
```
Comment (ferristseng) [inline app/models/tasks/assign_hearing_disposition_task.rb:144]: This seems like it would work, but I'm a bit confused because it looks like:

  * `AssignHearingDispositionTask` delegates `hearing` to `hearing_task`, and
  * `hearing_task` delegates `hearing` to `hearing_task_association`
  * So it seems like there should it already be a hearing task association

Is there some data that suggests that this is where the problem is?

File: spec/feature/hearings/change_hearing_disposition_spec.rb [hunk 6]
```diff
@@ -87,24 +87,43 @@
...
+        click_on veteran_link_text
+      end
+
+      step "change the hearing disposition to postponed" do
+        click_dropdown(prompt: "Select an action", text: "Change hearing disposition")
+        click_dropdown({ prompt: "Select", text: "Postponed" }, find(".cf-modal-body"))
+        fill_in "Notes", with: instructions_text
+        click_button("Submit")
+
+        allow(Raven).to receive(:capture_exception).with(ActiveRecord::RecordInvalid) { @raven_called = true }
```
Comment (ferristseng) [inline spec/feature/hearings/change_hearing_disposition_spec.rb:125]: Should this be `expect` instead of `allow`?

I don't think the block is needed either if you use `expect` because that assertion will fail if it's not called at all (you would have to move this line up to the top of the test).

File: spec/feature/hearings/change_hearing_disposition_spec.rb [hunk 7]
```diff
@@ -87,24 +87,43 @@
...
+      step "return to the hearing admin organization queue and verify that the task is no longer there" do
+        click_queue_switcher COPY::CASE_LIST_TABLE_QUEUE_DROPDOWN_TEAM_CASES_LABEL % HearingAdmin.singleton.name
+        expect(page).to have_content("Unassigned (0)")
+      end
     end
 
-    step "return to the hearing admin organization queue and verify that the task is no longer there" do
-      click_queue_switcher COPY::CASE_LIST_TABLE_QUEUE_DROPDOWN_TEAM_CASES_LABEL % HearingAdmin.singleton.name
-      expect(page).to have_content("Unassigned (0)")
+    scenario "with missing hearing task association" do
```
Comment (ferristseng) [inline spec/feature/hearings/change_hearing_disposition_spec.rb:112]: This test seems to have the same context as the above test -- do you need to adjust the context here?

File: app/models/tasks/assign_hearing_disposition_task.rb (hunk 5 above)
Comment (sahalliburton) [reply app/models/tasks/assign_hearing_disposition_task.rb:144]: I added this based on what Rubaiyat added as a previous solution: https://dsva.slack.com/archives/CHX8FMP28/p1575920065084200?thread_ts=1575556723.017300&cid=CHX8FMP28

File: app/controllers/tasks_controller.rb (hunk 4 above)
Comment (sahalliburton) [reply app/controllers/tasks_controller.rb:101]: I didnt want to lose the error, and the UI is not able to receive the error at the moment because it immediately redirects the user away from the page so there is not a way to show the error message right now without refactoring the modal and potentially parts of the QueueApp container

File: client/app/queue/ChangeHearingDispositionModal.jsx (hunk 3 above)
Comment (sahalliburton) [reply client/app/queue/ChangeHearingDispositionModal.jsx:88]: It doesnt need it, but I usually follow this pattern of consistency such that if I add safe-assign on a ternary I add it on both sides

File: app/controllers/tasks_controller.rb (hunk 4 above)
Comment (ferristseng) [reply app/controllers/tasks_controller.rb:101]: While the error can't be processed on the frontend, I think it would still be useful to see a status code from the network tab. I'm not actually sure what status code Rails returns when there's no render statement, but I'm guessing its a 200 (?).

Comment (sahalliburton) [reply app/controllers/tasks_controller.rb:101]: The error I was receiving on the frontend in the network tab after adding the above line was a 422 (Entity not-processable)

File: app/models/tasks/assign_hearing_disposition_task.rb (hunk 5 above)
Comment (ferristseng) [reply app/models/tasks/assign_hearing_disposition_task.rb:144]: The fix itself should work, but I'm wondering how `hearing` would exist if `hearing_task_association` is nil and if this aligns with the data in production? `hearing_task` will look at the `hearing_task_association` to find `hearing`, so wouldn't the `check_hearing_exists` check fail first?

Comment (ferristseng) [reply app/models/tasks/assign_hearing_disposition_task.rb:144]: In a more simpler way (because I'm bad at explaining thing 😅), if `hearing_task_association` is ever nil, then `check_hearing_exists` will fail before it (I think?).
