### PR TITLE
Fix Hearing Location on Hearing Details

### LINKED ISSUE #10073: Update hearing location in Hearing Details
Hearing location needs to be updated to reflect Washington, DC for Central Office hearings. It was showing the VACOLS RO as hearing location.

Screen Shot 2019-03-20 at 11 56 25 AM

### PR DESCRIPTION
**Pull request by ferristseng**
Resolves #10073 

### Description

- Refactors `to_hash` logic to serializers for Hearing and LegacyHearing.
- Implement and serialize `readableLocation` for Hearing. This was being used on the frontend, but didn't exist for non-legacy hearings.

### CODE REVIEW

File: app/serializers/hearings/hearing_serializer_base.rb [hunk 1]
```diff
@@ -0,0 +1,35 @@
+# frozen_string_literal: true
+
+module HearingSerializerBase
+  extend ActiveSupport::Concern
+
+  class_methods do
```
Comment (ferristseng) [inline app/serializers/hearings/hearing_serializer_base.rb]: This section was causing a lot of issues for reek. These are intended to act as alternate constructors for the serializers. I ignored both the warnings because it seems like it would introduce more complexity if I fixed them.

File: app/models/legacy_hearing.rb [hunk 2]
```diff
@@ -100,7 +100,9 @@ def hearing_day
   end
 
   def regional_office_key
-    return (venue_key || appeal&.regional_office_key) if request_type == "T" || hearing_day.nil?
+    if request_type == HearingDay::REQUEST_TYPES[:travel] || hearing_day.nil?
```
Comment (ferristseng) [inline app/models/legacy_hearing.rb]: Made this use the variable instead of the `"T"`

File: client/app/hearings/components/AssignHearingsTabs.jsx [hunk 3]
```diff
@@ -175,10 +175,6 @@ export default class AssignHearingsTabs extends React.Component {
 
   };
 
-  getHearingLocation = (hearing) => (
-    hearing.readableRequestType === 'Central' ? 'Washington, DC' : hearing.readableLocation
-  );
-
```
Comment (sharonwarner) [inline client/app/hearings/components/AssignHearingsTabs.jsx]: Yay!
