### PR TITLE
Dispatch tests to FACOLS

### LINKED ISSUE #5686: Move Dispatch tests to FACOLS
Dispatch tests in the following files are failing. We need to move them to FACOLS.

```
spec/feature/dispatch/establish_claim_spec.rb
spec/jobs/prepare_establish_claim_tasks_job_spec.rb
spec/models/claim_establishment_spec.rb
spec/models/establish_claim_spec.rb
```

### PR DESCRIPTION
**Pull request by sharonwarner**
Resolves #5686

### CODE REVIEW

File: spec/feature/dispatch/establish_claim_spec.rb [hunk 1]
```diff
@@ -719,10 +754,10 @@
         expect(page).to have_content("Cannot edit end product")
 
         # Make sure note page contains the special issues
-        expect(find_field("VBMS Note").value).to have_content("Private Attorney or Agent, and Rice Compliance")
+        expect(find_field("VBMS Note").value).to have_content("Rice Compliance")
```
Comment (sharonwarner) [inline spec/feature/dispatch/establish_claim_spec.rb]: I think this is an actual bug. 

https://github.com/department-of-veterans-affairs/caseflow/issues/7366
