### PR TITLE
Fix few virtual hearing related issues

### LINKED ISSUE #13763: Resolve Pexip and credential issues for virtual hearings
## Description
After behavior seen in the end-to-end testing 3/19/20, work through the following issues related to Pexip and the job(s) associated:

- [ ] Log full response from Pexip API
- [ ] Only send email if conference ID is set
- [ ] Change (in job) to `or` instead of `and` - currently we create the conference if the ID and alias are both nil
- [ ] Increase timeout for Pexip request
- [ ] Output status code
- [ ] Delete conferences job tries to send email to judge
- [ ] Add logging to delete conferences job
- [ ] Credentials are not being deployed correctly (Pexip password is cut off)

### PR DESCRIPTION
**Pull request by rubaiyat22**
Resolves #13763 
- add more logging in CreateConferenceJob and DeleteConferenceJob
- ensure judge does not receive cancellation emails
- increase timeout for pexip request
-  few logic changes in CreateConferenceJob
- few small nit changes to Response.rb

Acceptance Criteria
- [x] Log full response from Pexip API
- [x] Only send email if conference ID is set
- [x] Change (in job) to `or` instead of `and` - currently we create the conference if the ID and alias are both nil
- [x] Increase timeout for Pexip request
- [x] Output status code
- [x] Delete conferences job does not to send email to judge
- [x] Add logging to delete conferences job

### CODE REVIEW

File: app/jobs/virtual_hearings/create_conference_job.rb [hunk 1]
```diff
@@ -62,6 +64,7 @@ def set_virtual_hearing(hearing_id, hearing_type)
     end
   end
 
+  # rubocop:disable Metrics/AbcSize
```
Comment (rubaiyat22) [inline app/jobs/virtual_hearings/create_conference_job.rb]: Ignoring because just adding another log statement here was giving me `Assignment Branch Condition size for create_conference is too high. [32.08/30]`

File: app/jobs/virtual_hearings/create_conference_job.rb [hunk 2]
```diff
@@ -72,15 +75,17 @@ def create_conference
     )
 
     if resp.error
-      Rails.logger.warn "CreateConferenceJob failed: #{resp.error.message}"
+      Rails.logger.info("Pexip response: #{resp}")
+      Rails.logger.error "CreateConferenceJob failed: (#{resp.error.code}) #{resp.error.message}"
 
-      virtual_hearing.establishment.update_error!(resp.error.message)
+      virtual_hearing.establishment.update_error!("(#{resp.error.code}) #{resp.error.message}")
```
Comment (ferristseng) [inline app/jobs/virtual_hearings/create_conference_job.rb]: Nice idea here to store the response code too with the error!

File: .reek.yml [hunk 3]
```diff
@@ -56,8 +56,7 @@ detectors:
       - ClaimReviewAsyncStatsReporter#as_csv
       - DataIntegrityChecksJob
       - DecisionIssueSyncJob
-      - VirtualHearings::DeleteConferencesJob#delete_conference
-      - VirtualHearings::DeleteConferencesJob#process_virtual_hearing
+      - VirtualHearings::DeleteConferencesJob
```
Comment (ferristseng) [inline .reek.yml]: Does this change need to be made? I think it's better to be more specific when possible when excluding rules.

File: app/services/external_api/pexip_service/response.rb [hunk 4]
```diff
@@ -40,13 +39,13 @@ def check_for_error
     end
   end
 
-  def error_message(resp)
-    return "No error message" if resp.raw_body.empty?
+  def error_message
+    return "No error message from Pexip" if resp.raw_body.empty?
```
Comment (ferristseng) [inline app/services/external_api/pexip_service/response.rb]: Nice! This is clearer now that the error message is a Caseflow one.

File: app/models/hearings/forms/base_hearing_update_form.rb [hunk 5]
```diff
@@ -104,9 +104,11 @@ def email_sent_flag(attr_key)
 
   def virtual_hearing_updates
     # The email sent flag should always be set to false if any changes are made.
+    # The judge_email_sent flag should not be set to false if virtual hearing is cancelled.
     emails_sent_updates = {
       veteran_email_sent: email_sent_flag(:veteran_email),
-      judge_email_sent: email_sent_flag(:judge_email),
+      judge_email_sent: email_sent_flag(:judge_email) ||
+                        (!virtual_hearing_attributes.blank? && virtual_hearing_attributes[:status] == :cancelled),
```
Comment (ferristseng) [inline app/models/hearings/forms/base_hearing_update_form.rb]: This looks good! Would it also be possible to setup `VirtualHearings::SendEmail` to never send a cancellation email to the judge at all - just as a fallback incase this method fails (I wouldn't want judges receiving mysterious blank emails).

File: .reek.yml (hunk 3 above)
Comment (rubaiyat22) [reply .reek.yml]: I added this because all the methods in DeleteConferencesJob was getting flagged by codeclimate but i can be specific
