### PR TITLE
Fix test flakes

### LINKED ISSUE #13459: [Flaky Test] Higher-Level Review Add / Remove Issues page Veteran with future ratings
## Background/context/resources

```
  1) Higher-Level Review Add / Remove Issues page Veteran with future ratings when show_future_ratings featuretoggle is enabled 
     Failure/Error: expect(higher_level_review.receipt_date).to eq(receipt_date)

       expected: Sat, 25 May 2019
            got: Tue, 30 Apr 2019

       (compared using ==)

       Diff:
       @@ -1,2 +1,2 @@
       -Sat, 25 May 2019
       +Tue, 30 Apr 2019
     # ./spec/feature/intake/higher_level_review_spec.rb:701:in `block (4 levels) in <top (required)>'
```

 - Circle CI Error: https://app.circleci.com/jobs/github/department-of-veterans-affairs/caseflow/102457/parallel-runs/4/steps/4-120
 - Has the test already been skipped in the code?
   - [ ] Skipped
   - [x] Not Skipped
 - Related Flakes
    + 

## Approach

Time box this investigation and fix.

Remember that if a test has been skipped for a decent amount of time, it may no longer map to the exact code.

If you reach the end of your time box and don't feel like the solution is in sight:
  - [ ] document the work you've done, including dead ends and research
  - [ ] skip the test in the code
  - [ ] file a follow on ticket
  - [ ] close this issue

### PR DESCRIPTION
**Pull request by pkarman**
Fixes #13459 and some others that will become flakes once we randomize spec order.

### CODE REVIEW

File: spec/requests/api/v3/decision_review/higher_level_reviews_controller_spec.rb [hunk 1]
```diff
@@ -399,32 +399,38 @@ def get_higher_level_review # rubocop:disable Naming/AccessorMethodName
           expect(subject.first["ineligible"]).to be_nil
         end
 
-        it "should have an ineligible object" do
-          request_issue_in_active_review = create(
-            :request_issue,
-            decision_date: Time.zone.today - 5.days,
-            decision_review: create(:higher_level_review, id: 10, veteran_file_number: veteran.file_number),
```
Comment (edmangimelli) [inline spec/requests/api/v3/decision_review/higher_level_reviews_controller_spec.rb]: i'm curious as to why this line had been written this way originally --declaring an id explicitly

File: spec/requests/api/v3/decision_review/higher_level_reviews_controller_spec.rb [hunk 2]
```diff
@@ -399,32 +399,38 @@ def get_higher_level_review # rubocop:disable Naming/AccessorMethodName
...
-            contested_rating_issue_reference_id: "hlr123",
-            contention_reference_id: "2222",
-            end_product_establishment: create(:end_product_establishment, :active),
-            contention_removed_at: nil,
-            ineligible_reason: nil
-          )
-          ineligible_request_issue = create(
-            :request_issue,
-            decision_date: Time.zone.today - 3.days,
-            decision_review: create(:higher_level_review, id: 11, veteran_file_number: veteran.file_number),
```
Comment (edmangimelli) [inline spec/requests/api/v3/decision_review/higher_level_reviews_controller_spec.rb]: same as line 406
>i'm curious as to why this line had been written this way originally --declaring an id explicitly

File: spec/requests/api/v3/decision_review/higher_level_reviews_controller_spec.rb [hunk 3]
```diff
@@ -399,32 +399,38 @@ def get_higher_level_review # rubocop:disable Naming/AccessorMethodName
...
         end
 
-        it "should have an ineligible object" do
-          request_issue_in_active_review = create(
-            :request_issue,
-            decision_date: Time.zone.today - 5.days,
-            decision_review: create(:higher_level_review, id: 10, veteran_file_number: veteran.file_number),
-            contested_rating_issue_reference_id: "hlr123",
-            contention_reference_id: "2222",
-            end_product_establishment: create(:end_product_establishment, :active),
```
Comment (edmangimelli) [inline spec/requests/api/v3/decision_review/higher_level_reviews_controller_spec.rb]: this isn't needed, eh?

File: spec/requests/api/v3/decision_review/higher_level_reviews_controller_spec.rb [hunk 4]
```diff
@@ -399,32 +399,38 @@ def get_higher_level_review # rubocop:disable Naming/AccessorMethodName
...
+            create(
+              :request_issue,
+              decision_date: Time.zone.today - 5.days,
+              decision_review: create(:higher_level_review, veteran_file_number: veteran.file_number),
+              contested_rating_issue_reference_id: contested_issue_id,
+              contention_reference_id: "2222",
+              contention_removed_at: nil,
+              ineligible_reason: nil
+            )
+          end
```
Comment (edmangimelli) [inline spec/requests/api/v3/decision_review/higher_level_reviews_controller_spec.rb]: I'm not sure I understand the point of creating this request issue, if it isn't a request issue of `higher_level_review` (but rather of a newly created HLR)

File: spec/requests/api/v3/decision_review/higher_level_reviews_controller_spec.rb [hunk 5]
```diff
@@ -399,32 +399,38 @@ def get_higher_level_review # rubocop:disable Naming/AccessorMethodName
...
+          let!(:ineligible_request_issue) do
+            create(
+              :request_issue,
+              decision_date: Time.zone.today - 3.days,
+              decision_review: higher_level_review,
+              contested_rating_issue_reference_id: contested_issue_id,
+              contention_reference_id: "3333",
+              ineligible_reason: :duplicate_of_rating_issue_in_active_review,
+              ineligible_due_to: request_issue_in_active_review
```
Comment (pkarman) [inline spec/requests/api/v3/decision_review/higher_level_reviews_controller_spec.rb]: @edmangimelli we need `request_issue_in_active_review` to exist so that the ineligible request issue can reference it.

File: spec/requests/api/v3/decision_review/higher_level_reviews_controller_spec.rb (hunk 1 above)
Comment (pkarman) [reply spec/requests/api/v3/decision_review/higher_level_reviews_controller_spec.rb]: not sure. but we should never explicitly declare id values.

File: spec/requests/api/v3/decision_review/higher_level_reviews_controller_spec.rb (hunk 5 above)
Comment (edmangimelli) [reply spec/requests/api/v3/decision_review/higher_level_reviews_controller_spec.rb]: ah. whoops. missed that. thanks
