### PR TITLE
Fix Docket Order sorting in Assign Hearings tabs

### LINKED ISSUE #9437: Fix Sorting by Docket Number in Assign Hearings page
Appeals must appear in docket order within each category: CAVC, AOD and regular.

### PR DESCRIPTION
**Pull request by oscarAtNava**
Resolves #9437 

### Description
Fixed the sorting logic in AssignHearingsTabs to properly sort within each category: CAVC, AOD and normal.

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Go to Assign Hearings page
2. Go to Legacy Veterans Waiting tab
3. Confirm Veteran appeals are sorted by docket number within each category.

### CODE REVIEW

File: client/app/hearingSchedule/components/AssignHearingsTabs.jsx [hunk 1]
```diff
@@ -180,12 +180,12 @@ export default class AssignHearingsTabs extends React.Component {
 
     const sortedByAodCavc = _.sortBy(filtered, (appeal) => {
       if (appeal.attributes.caseType === LEGACY_APPEAL_TYPES_BY_ID.cavc_remand) {
-        return 0;
+        return `*${appeal.attributes.docketNumber}`;
```
Comment (mdbenjam) [inline client/app/hearingSchedule/components/AssignHearingsTabs.jsx]: Maybe just add a comment that explains the sort order that `*` and `+` gives us.

Comment (oscarAtNava) [reply client/app/hearingSchedule/components/AssignHearingsTabs.jsx]: Done
