### PR TITLE
Fix request issues seeds

### LINKED ISSUE #8679: [BE] Fix request issues seed data for local and demo environments

### PR DESCRIPTION
**Pull request by aroltsch**
Resolves #8679

### CODE REVIEW

File: db/seeds.rb [hunk 1]
```diff
@@ -478,18 +478,20 @@ def create_higher_level_reviews_and_supplemental_claims
...
     )
 
     untimely_request_issue = RequestIssue.create!(
       review_request: higher_level_review,
       issue_category: "Active Duty Adjustments",
-      description: "nonrating description",
+      nonrating_issue_description: "nonrating description",
       contention_reference_id: "12345",
       decision_date: Date.new(2018, 5, 1),
+      benefit_type: "compensation",
```
Comment (aroltsch) [inline db/seeds.rb]: Rake db:reset was failing for me due to request issue requiring benefit type
