### PR TITLE
Omit the Virtual Hearing RO from list of cities we test sorting

### LINKED ISSUE #15816: [Flaky Test] TaskPager.sorted_tasks - undefined method `upcase' for nil:NilClass
## Description
We keep seeing variants of [this](https://app.circleci.com/pipelines/github/department-of-veterans-affairs/caseflow/38315/workflows/895c3a79-ad71-4b52-b7f0-6bf31b2d7ed1/jobs/144654) flaky test:

**TaskPager.sorted_tasks when sorting by closest regional office column sorts by regional office city - spec.models.task_pager_spec**

```
Failure/Error: RegionalOffice::CITIES[task.appeal.closest_regional_office][:city].upcase.tr(" ", "_")

NoMethodError:
  undefined method `upcase' for nil:NilClass
./spec/models/task_pager_spec.rb:381:in `block (5 levels) in <top (required)>'
./spec/models/task_pager_spec.rb:380:in `each'
./spec/models/task_pager_spec.rb:380:in `sort_by'
./spec/models/task_pager_spec.rb:380:in `block (4 levels) in <top (required)>'
```

## Background/context/resources

 - Circle CI Error:  [TaskPager.sorted_tasks when sorting by closest regional office column sorts by regional office city - spec.models.task_pager_spec](https://app.circleci.com/pipelines/github/department-of-veterans-affairs/caseflow/38315/workflows/895c3a79-ad71-4b52-b7f0-6bf31b2d7ed1/jobs/144654)
 - Has the test already been skipped in the code?
   - [ ] Skipped
   - [x] Not Skipped

## Approach

Time box this investigation and fix.

Remember that if a test has been skipped for a decent amount of time, it may no longer map to the exact code.

If you reach the end of your time box and don't feel like the solution is in sight:
  - [ ] document the work you've done, including dead ends and research
  - [ ] skip the test in the code
  - [ ] file a follow on ticket
  - [ ] close this issue

### PR DESCRIPTION
**Pull request by n1zyy**
It has a null city which breaks the test. It should never be anyone's
closest office, though, so just omit it.

Resolves #15816

### Description
Fixes a flaky test. The virtual hearing office was recently added to `REGIONAL_OFFICE_INFORMATION.json`, but has a null city.

### CODE REVIEW

File: spec/models/task_pager_spec.rb [hunk 1]
```diff
@@ -363,9 +363,11 @@
 
     context "when sorting by closest regional office column" do
       let(:sort_by) { Constants.QUEUE_CONFIG.COLUMNS.REGIONAL_OFFICE.name }
+      let(:virtual_hearing_ro_key) { ['R'] }
```
Comment (n1zyy) [inline spec/models/task_pager_spec.rb:366]: Unnecessary variable assignment just to try to make `RegionalOffice::ROS - ['R']` more understandable.

File: spec/models/task_pager_spec.rb [hunk 2]
```diff
@@ -363,9 +363,11 @@
 
     context "when sorting by closest regional office column" do
       let(:sort_by) { Constants.QUEUE_CONFIG.COLUMNS.REGIONAL_OFFICE.name }
+      let(:virtual_hearing_ro_key) { ["R"] }
 
       before do
-        regional_offices = RegionalOffice::ROS
+        # Virtual Hearing "RO" has no city and should be omitted here:
```
Comment (yoomlam) [inline spec/models/task_pager_spec.rb:369]:
```suggestion
        # Virtual Hearing "R" has no city and should be omitted here:
```

Comment (yoomlam) [inline spec/models/task_pager_spec.rb:369]:
```suggestion
        # Regional Office "R" (Virtual Hearing) has no city and should be omitted here:
```

Comment (yoomlam) [reply spec/models/task_pager_spec.rb:369]: I don't think changing the test is the right solution if the `subject` (`TaskPager.new(arguments).task_page_count`) is able to handle null values. Shouldn't we update `expected_order` to handle null values?

**Review by yoomlam — CHANGES_REQUESTED** [review]
See comment.

File: spec/models/task_pager_spec.rb (hunk 2 above)
Comment (n1zyy) [reply spec/models/task_pager_spec.rb:369]: This seemed awfully reasonable when I talked to you this morning, but it seems like it might actually be more complicated.

To validate the concept, I changed the offending line to this:

```ruby
RegionalOffice::CITIES[task.appeal.closest_regional_office][:city].upcase.tr(" ", "_") rescue nil
```

Not the prettiest code, but wanted to see that it worked before making it more careful. This failed:

```
  1) TaskPager.sorted_tasks when sorting by closest regional office column sorts by regional office city
     Failure/Error:
       expected_order = created_tasks.sort_by do |task|
         RegionalOffice::CITIES[task.appeal.closest_regional_office][:city].upcase.tr(" ", "_") rescue nil
       end

     ArgumentError:
       comparison of NilClass with String failed
     # ./spec/models/task_pager_spec.rb:382:in `sort_by'
     # ./spec/models/task_pager_spec.rb:382:in `block (4 levels) in <top (required)>'
```

It looks like `sort_by` doesn't like a literal nil.


I changed it to `rescue ""`. Surprisingly, that affected the results:

```
  1) TaskPager.sorted_tasks when sorting by closest regional office column sorts by regional office city
     Failure/Error: expect(subject.map(&:appeal_id)).to eq(expected_order.map(&:appeal_id))

       expected: [1, 14, 6, 9, 13, 3, 8, 5, 10, 2, 4, 11, 12, 7]
            got: [14, 6, 9, 13, 3, 8, 5, 10, 2, 4, 11, 12, 7, 1]

       (compared using ==)
     # ./spec/models/task_pager_spec.rb:385:in `block (4 levels) in <top (required)>'
```

It seems like null values may actually be problematic here, but I pretty quickly ended up in TaskSorter code scratching my head.

Part of the reason I went with just removing virtual hearings is that @ferristseng had suggested they would never be anyone's closest office and that it therefore didn't really make sense to include them in the "when sorting by closest regional office column" test case. I'm inclined to either go with that approach, or to punt this for someone more familiar with the TaskSorter and expected behavior here.

Comment (yoomlam) [reply spec/models/task_pager_spec.rb:369]: Ok. How about adding a code comment to that effect, then I'll approve?

**Review by yoomlam — APPROVED** [review]
