### PR TITLE
Return an Error object instead of hash

### LINKED ISSUE #7944: [FE] Non-Error exception captured with keys: detail, status, title
Reference: https://github.com/getsentry/react-native-sentry/issues/391#issuecomment-438185109

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3019/
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3012/

### PR DESCRIPTION
**Pull request by aroltsch**
Resolves #7944 

This fixes two Sentry alerts: 
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3012/
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3019/events/205582/

### CODE REVIEW

File: client/app/queue/QueueActions.js [hunk 1]
```diff
@@ -515,7 +515,7 @@ const errorAllAttorneys = (error) => ({
 export const fetchAllAttorneys = () => (dispatch: Dispatch) =>
   ApiUtil.get('/users?role=Attorney').
     then((resp) => dispatch(receiveAllAttorneys(resp.body.attorneys))).
-    catch((error) => Promise.reject(dispatch(errorAllAttorneys(error))));
+    catch((error) => dispatch(errorAllAttorneys(error)));
```
Comment (aroltsch) [inline client/app/queue/QueueActions.js]: Removing Promise.reject solves the issue

Before:
image


After: 
image

Comment (mdbenjam) [reply client/app/queue/QueueActions.js]: Haha love the Before and After shot.
