### PR TITLE
Fix bug for no upcoming hearing days for RO17 and RO18

### LINKED ISSUE #11764: Uncaught TypeError: Cannot read property 'room' of undefined for RO18 in test
In AssignHearings.jsx, selectedHearingDay.room is undefined so the following error: `Uncaught TypeError: Cannot read property 'room' of undefined` is thrown. Link: http://localhost:3000/hearings/schedule/assign?roValue=RO18

### PR DESCRIPTION
**Pull request by ferristseng**
Resolves #11764

### Description

  - Only return selected hearing day room if selected hearing day is defined
  - Test to make sure the above fix is working

### CODE REVIEW

File: spec/feature/hearings/schedule_veteran_spec.rb [hunk 1]
```diff
@@ -509,4 +509,12 @@ def navigate_to_schedule_veteran_modal
       expect(page).to have_content(COPY::SCHEDULE_VETERAN_SUCCESS_MESSAGE_DETAIL)
     end
   end
+
+  context "No upcoming hearing days" do
```
Comment (rubaiyat22) [inline spec/feature/hearings/schedule_veteran_spec.rb]: I'm not sure if this test is necessary. Please let me know if this needs to be kept or discarded.

Comment (sharonwarner) [reply spec/feature/hearings/schedule_veteran_spec.rb]: I think it makes sense to keep!

File: client/app/hearings/components/AssignHearings.jsx [hunk 2]
```diff
@@ -58,14 +58,25 @@ const UpcomingHearingDaysNav = ({
   </div>
 );
 
+UpcomingHearingDaysNav.propTypes = {
```
Comment (sharonwarner) [inline client/app/hearings/components/AssignHearings.jsx]: 👍
