### PR TITLE
Fix bug in full_grant_decided_after

### LINKED ISSUE #426: Create Background Job to import Tasks
Create a background job that will nightly check for full and partial grants and create establish claim tasks for them.

Prerequisites:
- [x] Manually install and associate a redis instance for dev, UAT and prod (devops task) https://github.com/department-of-veterans-affairs/appeals-deployment/issues/136
- [x] Add redis support in code to caseflow #313 
- [x] Add support for background jobs to Caseflow (via sidekiq) (https://github.com/department-of-veterans-affairs/appeals-deployment/issues/197)

background job PR: https://github.com/department-of-veterans-affairs/caseflow-certification/pull/432

### PR DESCRIPTION
**Pull request by joofsh**
Fixes #426

### CODE REVIEW

File: spec/jobs/create_establish_claim_tasks_job_spec.rb [hunk 1]
```diff
@@ -7,7 +7,7 @@
 
     allow(AppealRepository).to receive(:remands_ready_for_claims_establishment).and_return([@partial_grant])
     allow(AppealRepository).to receive(:amc_full_grants).and_return([@full_grant])
-    Timecop.freeze(Time.zone.local(2015, 1, 10, 12, 8, 0))
+    Timecop.freeze(Time.zone.local(2015, 2, 1, 12, 8, 0))
```
Comment (joofsh) [inline spec/jobs/create_establish_claim_tasks_job_spec.rb]: Updated the tests to account for the scenario that arose here (being at the beginning of a new month)
