### PR TITLE
Fix flakey dropdown menu feature test behavior

### LINKED ISSUE #9396: Flakey test in hearing details feature spec
the *Hearing Coordinator* dropdown on the Hearing Details page isn't responding to the `click_dropdown` method in the ["User can update fields" hearing details feature spec.](https://github.com/department-of-veterans-affairs/caseflow/blob/master/spec/feature/hearing_schedule/hearing_details_spec.rb#L30).

Examples of the flake on Circle: [one](https://circleci.com/gh/department-of-veterans-affairs/caseflow/42582), [two](https://circleci.com/gh/department-of-veterans-affairs/caseflow/42920), [three](https://circleci.com/gh/department-of-veterans-affairs/caseflow/42922).

screenshot_2019-02-13-18-23-22 069

It's always the same dropdown; it's in the selected state but shows no menu.

### PR DESCRIPTION
**Pull request by tomas-nava**
Resolves #9396

### Description
Checks to make sure the dropdown menu has appeared before trying to select from it; tries clicking on the component again if it hasn't appeared.

### CODE REVIEW

File: spec/support/feature_helper.rb [hunk 1]
```diff
@@ -71,6 +71,29 @@ def find_dropdown(options, container)
     container.find(selector, **keyword_args)
   end
 
+  # sometimes the dropdown menu hasn't appeared after the first click
```
Comment (pkarman) [inline spec/support/feature_helper.rb]: I wonder if there's a way to leverage the capybara `find` wait time that already does this kind of timeout/try thing? Otherwise, this looks like a decent workaround.

Comment (tomas-nava) [reply spec/support/feature_helper.rb]: Good question...nothing shows up in a cursory search but I'll keep it in mind.
