### PR TITLE
Daily docket updates for AMA hearings

### LINKED ISSUE #8797: Daily Docket | AMA hearings
We need to ensure that the hearing schedule daily docket functionality works for AMA hearings. We should also add a feature test for AMA hearings.

Also, CO times are wrong on the daily docket.

### PR DESCRIPTION
**Pull request by sharonwarner**
Resolves #8797 

To test: 

Add an AMA hearing, Navigate to its daily docket, Update the hearing, Confirm the updates save.
Add an AMA hearing, Navigate to its daily docket, Postpone the hearing, Confirm the new hearing is created.

### CODE REVIEW

File: app/models/hearing.rb [hunk 1]
```diff
@@ -87,6 +93,13 @@ def current_issue_count
   end
   #:nocov:
 
+  def slot_new_hearing(hearing_day_id, _scheduled_time_unused, _appeal_unused)
+    # These fields are needed for the legacy hearing's version of this method
```
Comment (lomaxap) [inline app/models/hearing.rb]: should this be a class method and not an instance method?

Comment (lomaxap) [inline app/models/hearing.rb]: Should this be a class method and not an instance method?
