### PR TITLE
Redirect mixed case CSS_IDs in URL

### LINKED ISSUE #13912: Handle mixed case css_ids when navigating to a judge's assign queue
As of #13433, when a mixed case css_id is used in /queue/<css_id>/assign, we claim the css_id is incorrect. Instead, we should upcase all requests to find the right user and fix the URL to display correctly

Correct css_id
Screen Shot 2020-04-07 at 12 02 33 PM

Mixed Case css_id
Screen Shot 2020-04-07 at 12 10 28 PM
```json
// 20200420142307
// http://localhost:3000/queue/BVAAAbshire/assign

{
  "errors": [
    {
      "status": 400,
      "title": "\"BVAAAbshire\" is not a valid CSS_ID or user ID",
      "detail": "\"BVAAAbshire\" is not a valid CSS_ID or user ID"
    }
  ]
}
```

### AC
- [ ] When a user provides an incorrectly cased css_id, the URL is updated to the all caps css_id
- [ ] When a user provides an incorrectly cased css_id, the back end returns the correct user for the upcased css_id

### PR DESCRIPTION
**Pull request by yoomlam**
Resolves #13912 

### Description
If the CSS_ID in the URL has a lowercase character, redirect to a URL using a proper uppercased CSS_ID, ensuring that other parts of the URL (e.g., path and query string) are retained.

### Acceptance Criteria
- [x] When a user provides an incorrectly cased css_id, the URL is updated to the all caps css_id
- [X] When a user provides an incorrectly cased css_id, the back end returns the correct user for the upcased css_id

### Testing Plan

For AC 1:
1. Go to http://localhost:3000/queue/BVAAAbshire/assign (see original ticket)
  - [ ] URL in browser should be corrected to http://localhost:3000/queue/BVAAABSHIRE/assign

For AC 2:
1. Go to http://localhost:3000/users?css_id=casper
  - [ ] Results shown with the correct user regardless of mixed case CSS_ID
2. Go to http://localhost:3000/user?css_id=BVAAABShire or http://localhost:3000/user?css_id=bVADHUDson
  - [ ] Result shown with the correct user regardless of mixed case CSS_ID

### User Facing Changes

Only the corrected URL is changed if CSS_ID has lowercase character(s).

### CODE REVIEW

**Comment by yoomlam** [comment]
Need help resolving linter/brakeman complaint about `params.permit!`.

File: app/controllers/legacy_tasks_controller.rb [hunk 1]
```diff
@@ -35,6 +33,35 @@ def index
...
+  end
+
+  def redirect_using_valid_cssid
+    params[:user_id] = to_valid_css_id(params[:user_id])
+
+    # Permit all parameters in order to call `redirect_to`, otherwise we get
+    # error "unable to convert unpermitted parameters to hash".
+    # This should be secure since we're not saving the params and
+    # the permitted params will be checked again after the redirect.
+    params.permit!
```
Comment (yoomlam) [inline app/controllers/legacy_tasks_controller.rb]: CodeClimate's Brakeman is complaining about this. Is there a better solution to setting params.permitted to true?
https://stackoverflow.com/questions/46029084/rails-unable-to-convert-unpermitted-parameters-to-hash

File: app/controllers/legacy_tasks_controller.rb [hunk 2]
```diff
@@ -92,11 +120,7 @@ def update
   private
 
   def user
-    @user ||= begin
-                return User.find(params[:user_id]) if positive_integer?(params[:user_id])
-
-                User.find_by(css_id: params[:user_id])
-              end
+    @user ||= positive_integer?(params[:user_id]) ? User.find(params[:user_id]) : User.find_by(css_id: params[:user_id])
```
Comment (yoomlam) [inline app/controllers/legacy_tasks_controller.rb:123]: Fixed bug. Should not `return` within a begin block as that will return from the method.

File: app/controllers/users_controller.rb [hunk 3]
```diff
@@ -34,6 +36,18 @@ def judge
 
   private
 
+  def css_id
+    @css_id ||= valid_css_id_or_nil
+  end
+
+  def valid_css_id_or_nil
+    return nil unless params[:css_id].presence
```
Comment (yoomlam) [inline app/controllers/users_controller.rb:44]: Treat blank CSS_ID as nil.

File: app/controllers/users_controller.rb [hunk 4]
```diff
@@ -34,6 +36,18 @@ def judge
...
+
+    return to_valid_css_id(params[:css_id]) if invalid_css_id?(params[:css_id])
```
Comment (yoomlam) [inline app/controllers/users_controller.rb:46]: Uppercasing of CSS_ID is already done by the User model https://github.com/department-of-veterans-affairs/caseflow/blob/57e746e91b91c82c9b5f4edac343bde9688b68d9/app/models/user.rb#L491
but we'll do it in the controller to correct the CSS_ID ASAP since `css_id` is used in many places in the controller.

File: spec/controllers/legacy_tasks_controller_spec.rb [hunk 5]
```diff
@@ -66,19 +66,34 @@
...
           expect(response.status).to eq 400
         end
       end
     end
+    context "CSS_ID in URL is in mixed case" do
+      let(:randomly_downcase) { ->(char) { [true, false].sample ? char.downcase : char } }
+
+      def downcase_random_characters(str)
+        str.chars.map(&randomly_downcase).join
+      end
```
Comment (yoomlam) [inline spec/controllers/legacy_tasks_controller_spec.rb:87]: Pulled `randomly_downcase` out to address CognitiveComplexity complaints. Defining `randomly_downcase` as a function didn't quell the complaint. Have a better solution?

File: spec/controllers/users_controller_spec.rb [hunk 6]
```diff
@@ -236,7 +249,7 @@
         end
       end
 
-      context "when a valid css_id parameter is provided" do
+      context "when a valid id parameter is provided" do
```
Comment (yoomlam) [inline spec/controllers/users_controller_spec.rb:252]: Unrelated: fixed typo.

File: app/controllers/legacy_tasks_controller.rb [hunk 7]
```diff
@@ -35,6 +33,34 @@ def index
     end
   end
 
+  def invalid_parameters?
+    return redirect_using_valid_cssid if invalid_css_id?(params[:user_id])
```
Comment (yoomlam) [inline app/controllers/legacy_tasks_controller.rb:37]: Heart of PR. Remaining lines of this method are just a refactor of existing code.

File: app/controllers/legacy_tasks_controller.rb [hunk 8]
```diff
@@ -35,6 +33,34 @@ def index
...
+    fail(Caseflow::Error::InvalidUserId, user_id: params[:user_id]) unless user
+
+    return invalid_role_error unless ROLES.include?(user_role)
+
+    nil
+  end
+
+  def user_role
+    (params[:role] || user.vacols_roles.first).try(:downcase)
+  end
```
Comment (yoomlam) [inline app/controllers/legacy_tasks_controller.rb:48]: Refactor.

**Comment by yoomlam** [comment]
Hunter has [another approach](https://github.com/department-of-veterans-affairs/caseflow/compare/hschallhorn/replace-url-example?expand=1) that does the redirection in `QueueLoadingScreen.jsx`. 

The sequence of operations is:
1. user enters the URL
2. which routes to legacy_tasks_controller.rb
3. which render "queue/index"
4. which loads QueueApp.jsx
5. which loads QueueLoadingScreen.jsx
 
This PR does the redirection in step 2 (as soon as possible), thereby preventing a mixed-cased CSS_ID from propagating to `jsx` files and avoids having to correct the CSS_ID in the view or model.

Be aware that `User.find_by_css_id(user_css_id)` (which upcases the CSS_ID) doesn't behave like `User.find_by(css_id: user_css_id)`.

File: app/controllers/legacy_tasks_controller.rb [hunk 9]
```diff
@@ -35,6 +33,34 @@ def index
...
+
+    # Permit all parameters in order to call `redirect_to`, otherwise we get
+    # error "unable to convert unpermitted parameters to hash".
+    # This should be secure since we're not saving the params and
+    # the permitted params will be checked again after the redirect.
+    # For security, `only_path: true` will limit the redirect to the current host.
+    unchecked_params = params.merge(only_path: true).permit(params.keys)
+
+    # Default status is 302 Found (temporarily moved), so return 308 Permanent Redirect instead.
+    redirect_to(unchecked_params, status: :permanent_redirect)
```
Comment (yoomlam) [inline app/controllers/legacy_tasks_controller.rb:61]: No security holes since `params` will be checked after the redirect.

File: spec/controllers/legacy_tasks_controller_spec.rb (hunk 5 above)
Comment (hschallhorn) [reply spec/controllers/legacy_tasks_controller_spec.rb:87]: I think the other two tests are sufficient

File: spec/controllers/users_controller_spec.rb [hunk 10]
```diff
@@ -212,6 +212,19 @@
...
+
+        it "returns a valid response with the expected user" do
+          subject
+
+          expect(response.status).to eq(200)
+          response_body = JSON.parse(response.body)
+          expect(response_body["user"]["id"]).to eq(user.id)
+          expect(response_body["user"]["css_id"]).to eq(user.css_id)
+        end
+      end
```
Comment (hschallhorn) [inline spec/controllers/users_controller_spec.rb:227]: 👌

File: app/controllers/users_controller.rb (hunk 4 above)
Comment (hschallhorn) [reply app/controllers/users_controller.rb:46]: Think the `invalid_css_id?` check here is probably just as costly as blindly upcasing all css_ids. Can just return all upcased css_ids here.
```suggestion
    to_valid_css_id(params[:css_id])
```

File: app/controllers/users_controller.rb [hunk 11]
```diff
@@ -34,6 +36,18 @@ def judge
 
   private
 
+  def css_id
+    @css_id ||= valid_css_id_or_nil
```
Comment (hschallhorn) [inline app/controllers/users_controller.rb:40]: Suggestion below could leave this shortened to
```suggestion
    @css_id ||= params[:css_id].presence && to_valid_css_id(params[:css_id])
```

File: app/controllers/concerns/css_id_concern.rb [hunk 12]
```diff
@@ -0,0 +1,14 @@
...
+
+module CssIdConcern
+  extend ActiveSupport::Concern
+
+  # :reek:UtilityFunction
+  def invalid_css_id?(css_id)
+    css_id =~ /[a-z]/
+  end
+
+  def to_valid_css_id(css_id)
```
Comment (hschallhorn) [inline app/controllers/concerns/css_id_concern.rb:11]: Can we use the "normalize" as we use in [user.rb](https://github.com/department-of-veterans-affairs/caseflow/blob/57e746e91b91c82c9b5f4edac343bde9688b68d9/app/models/user.rb#L391)? Upcasing does not necessarily mean the css_id will be valid.
```suggestion
  def normalize_css_id(css_id)
```

File: app/controllers/concerns/css_id_concern.rb [hunk 13]
```diff
@@ -0,0 +1,14 @@
+# frozen_string_literal: true
+
+module CssIdConcern
+  extend ActiveSupport::Concern
+
+  # :reek:UtilityFunction
+  def invalid_css_id?(css_id)
```
Comment (hschallhorn) [inline app/controllers/concerns/css_id_concern.rb:7]: Can we use "normalize" as we use in [user.rb](https://github.com/department-of-veterans-affairs/caseflow/blob/57e746e91b91c82c9b5f4edac343bde9688b68d9/app/models/user.rb#L391)? Upcasing does not necessarily mean the css_id will be valid.
```suggestion
  def non_normalized_css_id?(css_id)
```

File: app/controllers/legacy_tasks_controller.rb [hunk 14]
```diff
@@ -35,6 +33,34 @@ def index
...
+    return invalid_role_error unless ROLES.include?(user_role)
+
+    nil
+  end
+
+  def user_role
+    (params[:role] || user.vacols_roles.first).try(:downcase)
+  end
+
+  def redirect_using_valid_cssid
```
Comment (hschallhorn) [inline app/controllers/legacy_tasks_controller.rb:50]: _Very_ nitpicky
```suggestion
  def redirect_using_valid_css_id
```

File: app/controllers/legacy_tasks_controller.rb (hunk 7 above)
Comment (hschallhorn) [inline app/controllers/legacy_tasks_controller.rb:37]: _Very_ nitpicky
```suggestion
    return redirect_using_valid_css_id if invalid_css_id?(params[:user_id])
```

File: app/controllers/legacy_tasks_controller.rb [hunk 15]
```diff
@@ -35,6 +33,34 @@ def index
...
+    params[:user_id] = to_valid_css_id(params[:user_id])
+
+    # Permit all parameters in order to call `redirect_to`, otherwise we get
+    # error "unable to convert unpermitted parameters to hash".
+    # This should be secure since we're not saving the params and
+    # the permitted params will be checked again after the redirect.
+    # For security, `only_path: true` will limit the redirect to the current host.
```
Comment (hschallhorn) [inline app/controllers/legacy_tasks_controller.rb:57]: 👌

File: app/controllers/legacy_tasks_controller.rb [hunk 16]
```diff
@@ -35,6 +33,34 @@ def index
...
+    return invalid_role_error unless ROLES.include?(user_role)
+
+    nil
+  end
+
+  def user_role
+    (params[:role] || user.vacols_roles.first).try(:downcase)
+  end
+
+  def redirect_using_valid_css_id
```
Comment (hschallhorn) [inline app/controllers/legacy_tasks_controller.rb:50]: Last normalized, I promise!
```suggestion
  def redirect_using_normalized_css_id
```

File: app/controllers/legacy_tasks_controller.rb [hunk 17]
```diff
@@ -35,6 +33,34 @@ def index
     end
   end
 
+  def invalid_parameters?
+    return redirect_using_valid_css_id if non_normalized_css_id?(params[:user_id])
```
Comment (hschallhorn) [inline app/controllers/legacy_tasks_controller.rb:37]:
```suggestion
    return redirect_using_normalized_css_id if non_normalized_css_id?(params[:user_id])
```
