### PR TITLE
correct virtual hearing link for hearing coordinators

### LINKED ISSUE #13153: Virtual hearings -incorrect link for hearings coordinator
Description: The hearings coordinator link to the virtual hearing is incorrect.
Observed: Hearing Coordinator link is guest. 
Expected: Hearing Coordinator link is VLJ (host) link
image

Note to developer: Please test in UAT prior to confirming complete.
Feature Flag: Same as all virtual hearings.

### PR DESCRIPTION
**Pull request by rubaiyat22**
Resolves #13153

### Description
- Users with role `Build HearSched` & `Edit HearSched` have the correct host virtual hearing link

### CODE REVIEW

File: client/app/hearings/components/details/DetailsInputs.jsx [hunk 1]
```diff
@@ -28,7 +34,7 @@ class DetailsInputs extends React.Component {
           <div {...css({ marginTop: '1.5rem' })}>
             {virtualHearing.jobCompleted &&
               <VirtualHearingLink
-                role={user.userId.toString() === hearing.judgeId ? 'host' : 'guest'}
+                role={this.role()}
```
Comment (ferristseng) [inline client/app/hearings/components/details/DetailsInputs.jsx]: Since the logic to determine the role is identical in both places, could we have a shared function to return this, or have the logic live inside the `VirtualHearingLink`?
