### PR TITLE
Fix virtual hearing type not displaying for days with held virtual hearings

### LINKED ISSUE #14101: Virtual not displaying in Type column of Hearing Schedule
#### Observed
The Type value for docket days before 4/24 on the Hearing Schedule page doesn't display Virtual, even when the dockets do in fact contain virtual hearings.

#### Steps to reproduce
1. Go to [Hearing Schedule ](https://appeals.cf.ds.va.gov/hearings/schedule)
1. Change "From" date in filter to 03/27/2020 (the first day virtual hearings were scheduled in Caseflow)
1. See that the Type of all docket days until 4/24 doesn't include Virtual

1. Open a docket day (like [3/27 Ft Harrison](https://appeals.cf.ds.va.gov/hearings/schedule/docket/4776) or [4/17 Atlanta](https://appeals.cf.ds.va.gov/hearings/schedule/docket/4954)) and see that the docket contains virtual hearings

#### Expected
Virtual displays in the Type column, and is a filterable value, for all docket days that contain virtual hearings.

### PR DESCRIPTION
**Pull request by ferristseng**
Resolves #14101

### Description

  * Removes `conference_deleted` part of where clause, which filters out held virtual hearings

Created a test case to replicate what is in production, and confirmed that it was failing. Adding this fix made the test pass

### CODE REVIEW

File: spec/queries/video_hearing_day_request_type_query_spec.rb [hunk 1]
```diff
@@ -79,6 +79,42 @@
...
+        )
+      end
+
+      it "sanity check: hearing is virtual" do
+        expect(hearing.reload.virtual?).to be true
+      end
+
+      include_examples "it returns correct hash with expected key and value",
+                       "Virtual"
+    end
```
Comment (tomas-nava) [inline spec/queries/video_hearing_day_request_type_query_spec.rb:116]:
```suggestion

      context "with a legacy hearing" do
        let(:disposition) { Constants.HEARING_DISPOSITION_TYPES.held }
        let(:hearing) { create(:legacy_hearing, disposition: disposition, hearing_day: hearing_day) }

        include_examples "it returns correct hash with expected key and value",
                         "Virtual"
      end
    end
```

I added this test for the `LegacyHearing` case when I was reviewing.
