### PR TITLE
Rescue EE JSON errors to silence sentry alerts

### LINKED ISSUE #13998: eFolder API returns JSON::ParserError: 783: unexpected token
Timebox investigation 

Related to #13571 the difference being the eFolder endpoint in this case is `/api/v2/document_counts`.  

The JSON parser returns a `JSON::ParserError: 783: unexpected token`.

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/9800

## Technical Notes
The error originates in `app/services/external_api/efolder_service.rb` in the `fetch_document_count` method.

### PR DESCRIPTION
**Pull request by pkarman**
See https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/9921/events/755143/

Resolves #13998

### Description
Treat EE invalid JSON as simple retry. We need to explore why nginx occasionally throws a 502 bad gateway, but we should treat EE as any other upstream service and handle failure more gracefully.

### CODE REVIEW

File: app/services/external_api/efolder_service.rb [hunk 1]
```diff
@@ -28,13 +28,25 @@ def self.document_count(file_number, user)
...
       response_body["documents"]
+    rescue JSON::ParserError => error
+      handle_json_parser_error(error)
+    end
+  end
+
+  def self.handle_json_parser_error(error)
+    if response.code != 200
+      # re-throw so we try again, but don't log to sentry
+      # these are likely 502 gateway errors from EE.
```
Comment (nanotone) [inline app/services/external_api/efolder_service.rb:46]: Might it be preferable to act conservatively and only call 5xx's transient? `!= 200` feels a tad too broad.

Comment (pkarman) [reply app/services/external_api/efolder_service.rb]: made explicit check for `502`
