### PR TITLE
Fix edge case where dispatched case has incomplete tasks

### LINKED ISSUE #12236: BVA progress SQL shows "dispatched" instead of "on hold"
Example where a `BvaDispatchTask` is completed but subsequent tasks are assigned.

```
Appeal 1849
└── RootTask 2019-03-12 16:16:49 UTC, on_hold, (closed_at)
    ├── TrackVeteranTask 2019-03-12 16:16:50 UTC, completed, 2019-03-12 16:16:50 UTC
    ├── TrackVeteranTask 2019-03-12 16:16:50 UTC, completed, 2019-03-12 16:16:50 UTC
    ├── TrackVeteranTask 2019-03-12 16:16:50 UTC, completed, 2019-03-12 16:16:50 UTC
    ├── TrackVeteranTask 2019-03-12 16:16:50 UTC, completed, 2019-03-12 16:16:50 UTC
    ├── DistributionTask 2019-03-12 16:16:50 UTC, completed, 2019-07-24 19:54:04 UTC
    │   ├── EvidenceSubmissionWindowTask 2019-03-12 16:16:50 UTC, completed, 2019-03-13 19:36:14 UTC
    │   └── InformalHearingPresentationTask 2019-03-19 05:30:04 UTC, cancelled, 2019-06-27 22:11:09 UTC
    ├── JudgeDecisionReviewTask 2019-03-13 19:39:23 UTC, completed, 2019-04-02 14:56:33 UTC
    │   └── AttorneyTask 2019-03-14 12:01:53 UTC, completed, 2019-03-23 22:07:53 UTC
    ├── EvidenceOrArgumentMailTask 2019-03-19 12:03:20 UTC, completed, 2019-03-20 18:39:28 UTC
    │   └── EvidenceOrArgumentMailTask 2019-03-19 12:03:20 UTC, completed, 2019-03-20 18:39:28 UTC
    │       └── EvidenceOrArgumentMailTask 2019-03-19 12:03:21 UTC, completed, 2019-03-20 18:39:28 UTC
    ├── EvidenceOrArgumentMailTask 2019-04-01 18:02:04 UTC, completed, 2019-04-09 15:11:59 UTC
    │   └── EvidenceOrArgumentMailTask 2019-04-01 18:02:04 UTC, completed, 2019-04-09 15:11:59 UTC
    │       └── EvidenceOrArgumentMailTask 2019-04-01 18:02:05 UTC, completed, 2019-04-09 15:11:59 UTC
    ├── BvaDispatchTask 2019-04-02 14:56:33 UTC, completed, 2019-04-10 14:51:48 UTC
    │   └── BvaDispatchTask 2019-04-02 14:56:34 UTC, completed, 2019-04-10 14:51:48 UTC
    ├── ReconsiderationMotionMailTask 2019-04-25 13:01:50 UTC, completed, 2019-06-18 18:17:20 UTC
    │   └── ReconsiderationMotionMailTask 2019-04-25 13:01:50 UTC, completed, 2019-06-18 18:17:20 UTC
    │       └── ReconsiderationMotionMailTask 2019-04-29 13:19:53 UTC, completed, 2019-06-18 18:17:20 UTC
    ├── EvidenceOrArgumentMailTask 2019-07-01 19:56:40 UTC, completed, 2019-07-03 15:02:51 UTC
    │   └── EvidenceOrArgumentMailTask 2019-07-01 19:56:40 UTC, completed, 2019-07-03 15:02:51 UTC
    │       └── EvidenceOrArgumentMailTask 2019-07-01 19:56:42 UTC, completed, 2019-07-03 15:02:51 UTC
    ├── JudgeAssignTask 2019-07-24 19:54:04 UTC, completed, 2019-08-26 10:44:12 UTC
    └── JudgeDecisionReviewTask 2019-08-26 10:44:12 UTC, on_hold, (closed_at)
        └── AttorneyTask 2019-08-26 10:44:13 UTC, on_hold, (closed_at)
            └── OtherColocatedTask 2019-09-26 13:17:52 UTC, on_hold, (closed_at)
                └── OtherColocatedTask 2019-09-26 13:17:58 UTC, assigned, (closed_at)
```

### PR DESCRIPTION
**Pull request by pkarman**
Resolves #12236 

### Description

Double-counting appeals since some have open tasks after `BvaDispatchTask` is complete.

### CODE REVIEW

File: app/sql/bva-decision-progress.sql [hunk 1]
```diff
@@ -76,6 +76,7 @@ WITH undistributed_appeals AS (select '1. Not distributed'::text as decision_sta
             WHERE tasks.type IN ('BvaDispatchTask') 
               AND tasks.appeal_type='Appeal'
               AND tasks.status IN ('completed')
+              AND tasks.appeal_id NOT IN (SELECT appeal_id FROM tasks WHERE tasks.appeal_type='Appeal' AND tasks.status IN ('on_hold', 'assigned', 'in_progress'))
```
Comment (lomky) [inline app/sql/bva-decision-progress.sql]: Might be worth throwing a note like "With no open tasks" in the comment for this section?

Comment (lomky) [inline app/sql/bva-decision-progress.sql]: Are there any tasks types we wouldn't want to check? I'm thinking about TrackVeteranTasks specifically

Comment (pkarman) [reply app/sql/bva-decision-progress.sql]: it's my understanding that if a `BvaDispatchTask` is completed, then the case is "complete" and all tasks should be closed -- unless they aren't, which is what we are finding in some situations. Those situations have to be dealt with one-at-a-time, but in this report should not double-count in the meantime.
