### PR TITLE
Sharon create task bug

### LINKED ISSUE #841: Admin Create Task Bug
Admins should be able to create tasks that go straight to the 'unassigned' state.

### PR DESCRIPTION
**Pull request by sharonwarner**
This PR allows admins to create tasks that automatically go to the 'unassigned' state. Admins will have to confirm that the appeal has a decision document before manually creating the task. 

Fixes #841

- [ ] Updated unit tests to confirm newly created task is in correct state

### CODE REVIEW

File: app/controllers/admin/establish_claims_controller.rb [hunk 1]
```diff
@@ -9,7 +9,9 @@ def show
   def create
     vbms_id = params[:appeal][:vbms_id]
     appeal = Appeal.find_or_create_by_vbms_id(vbms_id)
-    EstablishClaim.find_or_create_by(appeal: appeal)
+    establish_claim = EstablishClaim.find_or_create_by(appeal: appeal)
+    # Admin has to confirm appeal has a decision document
+    establish_claim.prepare! if establish_claim.may_prepare?
```
Comment (joofsh) [inline app/controllers/admin/establish_claims_controller.rb]: Thanks for fixing this 👍
