### PR TITLE
Fix median, and add test coverage

### LINKED ISSUE #16006: [Flaky Test] ClaimReviewAsyncStatsReporter#stats returns incorrect nested hash
## Description
```
ClaimReviewAsyncStatsReporter#stats returns nested hash - spec.services.claim_review_async_stats_reporter_spec
spec/services/claim_review_async_stats_reporter_spec.rb
Failure/Error:
  expect(subject).to eq(
    supplemental_claims: {
      total: 6,
      expired: 1,
      in_progress: 1,
      canceled: 1,
      processed: 4,
      established_within_seven_days: 3,
      established_within_seven_days_percent: 50.0,
      median: 50_400.0,

  expected: {:higher_level_reviews=>{:avg=>457200.0, :canceled=>1, :established_within_seven_days=>3, :establishe...ed=>1, :in_progress=>1, :max=>1738800.0, :median=>50400.0, :min=>14400.0, :processed=>4, :total=>6}}
       got: {:higher_level_reviews=>{:avg=>457200.0, :canceled=>1, :established_within_seven_days=>3, :establishe...ed=>1, :in_progress=>1, :max=>1738800.0, :median=>50400.0, :min=>14400.0, :processed=>4, :total=>6}}
```

## Background/context/resources

 - Circle CI Error:  https://app.circleci.com/pipelines/github/department-of-veterans-affairs/caseflow/39962/workflows/7f06f229-5ed6-4922-b58b-82d2241520b5/jobs/152724
 - Has the test already been skipped in the code?
   - [ ] Skipped
   - [x] Not Skipped
 - Related Flakes
    + 

## Approach

Time box this investigation and fix.

Remember that if a test has been skipped for a decent amount of time, it may no longer map to the exact code.

If you reach the end of your time box and don't feel like the solution is in sight:
  - [ ] document the work you've done, including dead ends and research
  - [ ] skip the test in the code
  - [ ] file a follow on ticket
  - [ ] close this issue

### PR DESCRIPTION
**Pull request by n1zyy**
Also fixes the old test that asserted incorrect behavior!

Fixes #16006

### Description
We ran into [this weird flake](https://app.circleci.com/pipelines/github/department-of-veterans-affairs/caseflow/39962/workflows/7f06f229-5ed6-4922-b58b-82d2241520b5/jobs/152724) recently.

I _think_ the immediate cause of the error was that we assumed the database output was in chronological order, but never used an `ORDER BY`, so there was no contract for the ordering.

But in looking at this, I was skeptical that `Reporter#median` was correct. I added some tests that prove it is--as long as the input sorted. Since that was clearly not always true, I made the method sort its input, since it returns nonsense otherwise. (Previously, the output was literally the middle value, so the "median" of `[1, 1, -10000, 1, 1]` would be `-10000` which is certainly not what statisticians would expect.)

"Fixing" the method broke the existing test (!), so I also fixed that.

### Acceptance Criteria
- [ ] Tests pass successfully

### CODE REVIEW

File: spec/services/claim_review_async_stats_reporter_spec.rb [hunk 1]
```diff
@@ -133,7 +133,7 @@
 
     it "returns CSV" do
       csv = subject
-      expect(csv).to match(/supplemental_claims,6,1,1,4,3,50.0,14:00:00,133:45:00,483:00:00,04:00:00/)
+      expect(csv).to match(/supplemental_claims,6,1,1,4,3,50.0,24:00:00,133:45:00,483:00:00,04:00:00/)
```
Comment (n1zyy) [inline spec/services/claim_review_async_stats_reporter_spec.rb:136]: These values were wrong! They were the middle or average-of-middle array elements in an out-of-order array, not the median values.

This makes me wonder a few things, though:

1. If the method was "wrong" and the test asserted that behavior, is it possible that this behavior was intentional? (I _think_ not; "return the middle of the array, or average the middle two if it's an even list" seems like odd functionality.)
2. If we've been reporting incorrect data, do we need to notify anyone? @nanotone suggests that consumers of these reports likely weren't too focused on median.
3. In that case, is the correct response to, "It turns out that we've been generating incorrect statistical data but it's OK because no one was relying on it," I wonder if the "fix" should be to just get rid of the median calculation?

File: spec/services/concerns/reporter_spec.rb [hunk 2]
```diff
@@ -0,0 +1,89 @@
...
+
+# frozen_string_literal: true
+
+describe Reporter do
+  class TestReporter
+    include Reporter
+  end
+
+  describe "#average" do
+    let(:thing) { TestReporter.new }
```
Comment (n1zyy) [inline spec/services/concerns/reporter_spec.rb:11]: Testing `average` was mostly to build confidence that I was properly implementing this new spec file.

I should probably rename `thing`...

File: spec/services/concerns/reporter_spec.rb [hunk 3]
```diff
@@ -0,0 +1,89 @@
...
+  end
+
+  describe "#median" do
+    let(:thing) { TestReporter.new }
+    subject { thing.median(items) }
+
+    describe "when called with an empty array" do
+      let(:items) { [] }
+
+      it "returns 0" do
```
Comment (n1zyy) [inline spec/services/concerns/reporter_spec.rb:45]: I suspect this is mathematically not quite true, but that returning 0 rather than raising an exception or returning nil is probably best for our reporting purposes.

File: spec/services/concerns/reporter_spec.rb [hunk 4]
```diff
@@ -0,0 +1,87 @@
...
+
+      it "returns that item" do
+        expect(subject).to eq 50
+      end
+    end
+
+    describe "when called with two items" do
+      let(:items) { [50, 52] }
+
+      it "returns the average?" do
```
Comment (n1zyy) [inline spec/services/concerns/reporter_spec.rb:60]:
```suggestion
      it "returns the average" do
```

Whoops, this started out as a question when I was trying to figure out what expected behavior was, but it's no longer a question. 😆

File: spec/services/claim_review_async_stats_reporter_spec.rb [hunk 5]
```diff
@@ -93,7 +93,7 @@
           processed: 4,
           established_within_seven_days: 3,
           established_within_seven_days_percent: 50.0,
-          median: 50_400.0,
+          median: 86_400.0,
```
Comment (rubaiyat22) [inline spec/services/claim_review_async_stats_reporter_spec.rb:96]: I'm assuming these numbers changed because of the change in median method

**Review by rubaiyat22 — APPROVED** [review]
great job on figuring this one out!! 
approved w/ some questions/comments

File: spec/services/claim_review_async_stats_reporter_spec.rb (hunk 5 above)
Comment (n1zyy) [reply spec/services/claim_review_async_stats_reporter_spec.rb:96]: Yes. This one in particular was being passed `[86400.0, 86400.0, 14400.0, 1738800.0]`. The old "literally just return the middle" was returning the midpoint of 86,400 and 14,400, but now that it's sorted, it's properly returning the true median of 86,400.

File: spec/services/claim_review_async_stats_reporter_spec.rb (hunk 1 above)
Comment (n1zyy) [reply spec/services/claim_review_async_stats_reporter_spec.rb:136]: I was. It seems like it was the same situation -- returning incorrect data, but with the error seemingly being of no consequence.

I think removing it might require too much back-and-forth, so I'll leave it for now.

Comment (n1zyy) [reply spec/services/claim_review_async_stats_reporter_spec.rb:136]: (As for who the consumers are&mdash;it's an excellent question, to which I don't know the answer.)

Comment (nanotone) [reply spec/services/claim_review_async_stats_reporter_spec.rb:136]: These stats get posted to #caseflow-vbms-intake on the 1st and 15th of every month, and to #appeals-job-alerts on the 1st of every month. There are a bunch of folks in each channel, but in recent times I've only heard of the Lighthouse team looking at the totals in the report.
