### PR TITLE
Fixing lack of time in hearings

### LINKED ISSUE #8004: Rescheduled Veteran for 8:30 AM time slot is saving to VACOLS as 3:30 AM.
Look at formatHearing in DailyDocketContainer.jsx and update in hearings_controller.rb. 

Discovered 11/27 in testing with Justin. He scheduled a video hearing through Caseflow. It saved correctly in VACOLS. 

When he went to test rescheduling from Caseflow Daily docket, the hearing date saved correctly in VACOLS (and Caseflow), but the hearing time appeared as 3:30 AM not 8:30 AM, as had been selected.

### PR DESCRIPTION
**Pull request by mdbenjam**
Resolves #8004

### Description
Pass a time object to the backend to specify when a hearing should be scheduled.

### CODE REVIEW

File: spec/controllers/hearings_controller_spec.rb [hunk 1]
```diff
@@ -24,6 +24,44 @@
...
+                       "m" => "00",
+                       "offset" => "-500"
+                     }
+                   },
+                   prepped: true
+                 }
+        patch :update, as: :json, params: { id: hearing.id, hearing: params }
+        expect(response.status).to eq 200
+
+        expect(VACOLS::CaseHearing.last.hearing_date).to eq(DateTime.new(2019, 4, 2, 10).in_time_zone("Eastern Time (US & Canada)"))
```
Comment (mdbenjam) [inline spec/controllers/hearings_controller_spec.rb]: It seems to store 9AM hearings at 10? Is that right?

File: spec/repositories/hearing_repository_spec.rb [hunk 2]
```diff
@@ -4,6 +4,34 @@
...
+        hearing_type: "C",
+        hearing_date: 1.day.from_now.to_s,
+        room_info: "123",
+        judge_id: "456",
+        regional_office: "RO18"
+      )
+    end
+
+    it "slots hearing at correct time" do
+      HearingRepository.slot_new_hearing(VACOLS::CaseHearing.first.hearing_pkseq, time, legacy_appeal)
```
Comment (sharonwarner) [inline spec/repositories/hearing_repository_spec.rb]: Might be easier to talk through this in person, but slot_new_hearing should take a parent_id. We should send HearingDay.first instead of VACOLS::CaseHearing.first.

File: spec/repositories/hearing_repository_spec.rb [hunk 3]
```diff
@@ -4,6 +4,34 @@
...
+      }
+    end
+    let(:staff_record) { create(:staff) }
+
+    before do
+      RequestStore.store[:current_user] = OpenStruct.new(vacols_uniq_id: staff_record.slogid)
+
+      HearingDay.create_hearing_day(
+        hearing_type: "C",
+        hearing_date: 1.day.from_now.to_s,
```
Comment (sharonwarner) [inline spec/repositories/hearing_repository_spec.rb]: I created a generator for hearing day that might be easier to use. The way it's written now, this will be a VACOLS hearing day for the next few months and then will turn into a Caseflow hearing day. I think we're ok just testing the Caseflow hearing days for this functionality.

File: spec/repositories/hearing_repository_spec.rb (hunk 2 above)
Comment (sharonwarner) [inline spec/repositories/hearing_repository_spec.rb]: When we update the function above, this will have to be HearingDay.first because the hearing day will be in Caseflow.
