### PR TITLE
Don't throw ActiveRecord::RecordNotFound in the wrong places

### LINKED ISSUE #1570: Eliminate the need to delete the case record's vbms id in fakes
In `lib/fakes/appeal_repository.rb`, `load_vacols_data` has the line `record.delete(:vbms_id) if Rails.env.development? && !appeal.vbms_id.nil?`

See https://github.com/department-of-veterans-affairs/caseflow/pull/1545, which was a fix for an issue created by the `record.delete(:vbms_id)` line, which was itself a quick fix for local dispatch being broken. Investigate how to mitigate the need for this janky behavior by refacroring. @shanear @joofsh and @amprokop will all have opinions on what needs to be done here.

### PR DESCRIPTION
**Pull request by shanear**
Instead, only throw `ActiveRecord::RecordNotFound` when we are explicitly loading the appeal in `Appeal.find_or_create_by_vacols_id` and `Appeal.find_or_create_by_vbms_id`. As an added bonus, this is more testable.

Add `vacols_record_exists?` method to `AssociatedVacolsModel` to check if the VACOLS record still exists for an appeal. This is used to invalidate `EstablishClaim` tasks.

This required some changes to `Fakes::AppealRepository` so fixed some issues we were having there as well.

connects #1535
fixes #1570

## Additional testing steps
- [x] test dispatch and certification locally after a fresh `rake db:seed`
- [ ]  test loading an non existent appeal in certification with real VACOLS
- [ ]  test assigning an establish claim with a missing appeal with real VACOLS

### CODE REVIEW

File: app/services/appeal_repository.rb [hunk 1]
```diff
@@ -32,9 +34,11 @@ def self.load_vacols_data(appeal)
     set_vacols_values(appeal: appeal, case_record: case_record)
 
     appeal
+
+  rescue ActiveRecord::RecordNotFound
+    return false
```
Comment (joofsh) [inline app/services/appeal_repository.rb]: this feels pretty awkward to me, so now this method will return either an `appeal` or `false`? I would prefer methods to only return 1 data type if possible. 

Would it make more sense to move the `rescue` to `perform_vacols_request`?

File: app/models/concerns/associated_vacols_model.rb [hunk 2]
```diff
@@ -16,7 +16,7 @@ def vacols_attr_accessor(*fields)
         end
 
         define_method "#{field}=" do |value|
-          check_and_load_vacols_data!
+          check_and_load_vacols_data! unless vacols_loading?
```
Comment (joofsh) [inline app/models/concerns/associated_vacols_model.rb]: why move the check out of `check_and_load_vacols_data!`. You're already checking for `unless vacols_complete?`

File: app/models/concerns/associated_vacols_model.rb [hunk 3]
```diff
@@ -32,16 +32,37 @@ def assign_from_vacols(values)
...
   end
 
-  # TODO(jd): consider adding a more sophisticated caching mechanism.
-  # Right now we are setting the @fetched_vacols_data to true before knowing
-  # if the DB request to VACOLS succeeded. This is required to avoid an infinite
-  # loop within the setters, but will not properly handle the case of VACOLS
-  # returning an error
   def check_and_load_vacols_data!
-    return if @fetched_vacols_data
+    perform_vacols_request unless vacols_complete?
```
Comment (joofsh) [inline app/models/concerns/associated_vacols_model.rb]: I think this could simply be `unless @vacols_load_status`. That way if any value has been assigned we don't re-perform the request

File: app/models/appeal.rb [hunk 4]
```diff
@@ -272,9 +272,10 @@ class << self
 
     def find_or_create_by_vacols_id(vacols_id)
       appeal = find_or_initialize_by(vacols_id: vacols_id)
-      repository.load_vacols_data(appeal)
-      appeal.save
 
+      fail ActiveRecord::RecordNotFound unless appeal.check_and_load_vacols_data!
```
Comment (joofsh) [inline app/models/appeal.rb]: I don't understand how this solves the issue with the missing decision page not loading. Won't `appeal.check_and_load_vacols_data!` return false if the record didn't exist, which will throw the error here?

File: app/services/appeal_repository.rb (hunk 1 above)
Comment (shanear) [inline app/services/appeal_repository.rb]: The return value is `truthy` or `falsey`. The fact that it returns an appeal is sort of irrelevant. Would changing line 36 to `true` which might be more clear?

File: app/models/concerns/associated_vacols_model.rb (hunk 3 above)
Comment (shanear) [inline app/models/concerns/associated_vacols_model.rb]: good call on these changes. That cleans this stuff up nicely. For whatever reason, this logic gave me a hard time lol

File: app/models/appeal.rb (hunk 4 above)
Comment (shanear) [inline app/models/appeal.rb]: The missing decision page never explicitly calls this method (it's used when all we have is a vacols id and we are loading the appeal).

The missing decisions page lazily loads vacols values on the appeal through the `vacols_attr_accessor` logic. When an appeal isn't found, those values will just be `nil`, and the missing decisions page will just render a bunch of blank values. That's a better outcome than the page crashing

File: app/services/appeal_repository.rb (hunk 1 above)
Comment (shanear) [inline app/services/appeal_repository.rb]: Didn't want to move the rescue to `perform_vacols_request` because it exposes a lot of the internals of how the data is loaded (ie. if we decided to ditch AR for VACOLS, then we'd have to jump more out of the `Repository` to make that change)

If you feel strongly about this i will still change though.

Comment (joofsh) [inline app/services/appeal_repository.rb]: oh gotcha, that makes sense. I thought we were using the `appeal` return value from 36
