### PR TITLE
hide ihp tasks on substitute if poa cannot write ihp tasks

### LINKED ISSUE #16431: [Flaky Test] case_details_spec.rb expects CASE_DETAILS_UNRECOGNIZED_POA
## Description

```
./spec/feature/queue/case_details_spec.rb:405:in `block (5 levels) in <top (required)>'
./spec/spec_helper.rb:23:in `block (2 levels) in <top (required)>'
```

```ruby
expect(page).to_not have_content(COPY::CASE_DETAILS_UNRECOGNIZED_POA)
```

## Background/context/resources

Case details attorney case details view when appellant is an attorney or unlisted claimant when an unrecognized appellant has a recognized POA details view contains POA information - spec.feature.queue.case_details_spec

 - Circle CI Error:  [Case details attorney case details view when appellant is an attorney or unlisted claimant when an unrecognized appellant has a recognized POA details view contains POA information - spec.feature.queue.case_details_spec](https://app.circleci.com/pipelines/github/department-of-veterans-affairs/caseflow/43988/workflows/8e7ab7dc-7fa8-49d8-9438-ef0b5ba90e5d/jobs/172141)
 - Has the test already been skipped in the code?
   - [ ] Skipped
   - [x] Not Skipped
 - Related Flakes
    + 

## Approach

Time box this investigation and fix.

Remember that if a test has been skipped for a decent amount of time, it may no longer map to the exact code.

If you reach the end of your time box and don't feel like the solution is in sight:
  - [ ] document the work you've done, including dead ends and research
  - [ ] skip the test in the code
  - [ ] file a follow on ticket
  - [ ] close this issue

### PR DESCRIPTION
**Pull request by barshirtcliff**
Resolves [CASEFLOW-1627](https://vajira.max.gov/browse/CASEFLOW-1627)
Resolves #16431

### Description
This adds a serializer for POAs, along with a variable, `ihp_allowed`, to be used in the frontend.  It also adjust the frontend logic to use that new variable.  The new variable checks the type of organization on the poa to see whether the new claimant's representative organization can write ihps.  Specifically, Field Vsos and Private Bars cannot write IHPs, so this makes it so the COB user won't see IHPs listed at substitution task-selection time, once they select a claimant with a Field VSO or Private Bar organization representing them.
I'm open to suggestions on where the organization-consulting logic can live.  I thought it best to put it into the serializer because it's only needed in a frontend context, but I would agree that it's somehow wrong to be querying the db there.  It could be a method on Bgs_power_of_attorney, rather.
**TO DO:**
- [ ] optimize db call for this if possible

### Acceptance Criteria
- [X] Code compiles correctly
- [X] New unit tests for added backend logic

### Testing Plan
updated unit tests.  To view the change in action:
1. Create the data situation:  use the new `with_ihp_task` trait to create an appeal, then mark the ihp task as completed:
```
RequestStore[:current_user] = User.system_user
appeal = FactoryBot.create(:appeal, :with_ihp_task, :dispatched_with_decision_issue,
         docket_type: "direct_review",
         stream_type: "original",
         disposition: "dismissed_death",               
         veteran_is_not_claimant: false)
appeal1.veteran.update(date_of_death: 1.day.ago) 
appeal.uuid
```
2. Navigate to caseflow and become a COB user, then navigate to the appeal you created at `http://localhost:3000/queue/appeals/<appeal-uuid>`
3. Click the button to add a substitute appellant
4. Select the first relationship, check the network tab and click on the `poa` call.  You should see the value for `ihp_allowed` match the display: if it's true, that task will be available, and if false, it will not.  Available relationships include all three potential setups: ihp-writing poa, non-ihp-writing-poa, and no poa.  No poa is currently configured to be non-ihp-writing, meaning that substitute appellants are not expected to represent themselves in an informal hearing presentation.

### CODE REVIEW

File: app/models/serializers/work_queue/power_of_attorney_serializer.rb [hunk 1]
```diff
@@ -0,0 +1,23 @@
+# frozen_string_literal: true
+
+class WorkQueue::PowerOfAttorneySerializer
```
Comment (jcq) [inline app/models/serializers/work_queue/power_of_attorney_serializer.rb:3]: Love that now we have a serializer for this! 🎉

File: app/models/serializers/work_queue/power_of_attorney_serializer.rb [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+  attribute :representative_type
+  attribute :file_number
+  attribute :authzn_change_clmant_addrs_ind
+  attribute :authzn_poa_access_ind
+  attribute :legacy_poa_cd
+  attribute :last_synced_at
+  attribute :created_at
+  attribute :updated_at
+
+  non_ihp_writing_org_types = %w[FieldVso PrivateBar]
```
Comment (jcq) [inline app/models/serializers/work_queue/power_of_attorney_serializer.rb:18]: Are there any other files where this might be useful? Was thinking perhaps it could be useful as a static method in `InformalHearingPresentationTask` or something, but also totally fine just leaving it here until needed elsewhere!

Comment (barshirtcliff) [reply app/models/serializers/work_queue/power_of_attorney_serializer.rb:18]: That makes sense to me - I'm happy to put it there, since it's a sensible place to look for such information.

File: app/models/organizations/field_vso.rb [hunk 3]
```diff
@@ -9,6 +9,10 @@ def queue_tabs
     ]
   end
 
+  def should_write_ihp?(_appeal)
+    false
+  end
```
Comment (lowellrex) [inline app/models/organizations/field_vso.rb:14]: Too much to take on as part of this ticket, but I did want to highlight that we may want to address this long-standing area for improvement in how we handle which VSOs write IHPs (https://github.com/department-of-veterans-affairs/caseflow/issues/12448).

😬 _Somebody_ created the `vso_config` table assuming that it would be used for many things but it currently exists to support the one edge case of PVA writing IHPs for all three AMA dockets (instead of the 2 that other colocated VSOs write IHPs for).

Can confirm [in Metabase](https://query.prod.appeals.va.gov/) with a query like:
```sql
select org.id
, org.name
, org.type
, conf.ihp_dockets
, conf.created_at
from vso_configs conf
join organizations org
  on org.id = conf.organization_id
order by 3;
```

Comment (barshirtcliff) [reply app/models/organizations/field_vso.rb:14]: > Too much to take on as part of this ticket, but I did want to highlight that we may want to address this long-standing area for improvement in how we handle which VSOs write IHPs (#12448).
> 
I can't nod my head hard enough to express my agreement.  This one outlier is an outstanding confusinator wrt how ihp-writing is governed.

File: app/models/serializers/work_queue/power_of_attorney_serializer.rb (hunk 2 above)
Comment (barshirtcliff) [reply app/models/serializers/work_queue/power_of_attorney_serializer.rb]: this is done.  dismissing comment (thank you!)

File: spec/feature/queue/case_details_spec.rb [hunk 4]
```diff
@@ -400,7 +400,7 @@
 
         let(:ua) { create(:unrecognized_appellant) }
 
-        scenario "details view contains POA information" do
+        scenario "details view contains POA information", skip: "flake" do
```
Comment (jcq) [inline spec/feature/queue/case_details_spec.rb:403]: Can we add a comment clarifying what was flaking w/ this?

Comment (barshirtcliff) [reply spec/feature/queue/case_details_spec.rb:403]: [This stacktrace](https://app.circleci.com/pipelines/github/department-of-veterans-affairs/caseflow/44047/workflows/b13f2cf5-00aa-4712-89e1-77b9a78feba9/jobs/172432/tests#failed-test-0) isn't very informative, really.  It just says, basically, that it failed.

File: app/controllers/claimants_controller.rb [hunk 5]
```diff
@@ -2,10 +2,11 @@
 
 class ClaimantsController < ApplicationController
   def refresh_claimant_poa
-    poa = BgsPowerOfAttorney.find_by(claimant_participant_id: params[:participant_id])
+    poa = BgsPowerOfAttorney.find_or_create_by_claimant_participant_id(params[:participant_id])
```
Comment (jcq) [inline app/controllers/claimants_controller.rb:5]: This appears to be working now, but just flagging that for the 3rd dependent (Brady), we get this API response:

```
Validation failed: Poa participant can't be blank, Representative name can't be blank, Representative type can't be blank
```

This is because the `participant_id` that is being passed is `no-such-pid`; this may well be the intended behavior, but did just want to flag!

Comment (jcq) [reply app/controllers/claimants_controller.rb:5]: Also def will want to chat with @eileen-nava about the reasons for the previous change to `find_by` — I don't recall what prompted that

File: spec/feature/queue/case_details_spec.rb [hunk 6]
```diff
@@ -402,7 +402,7 @@
 
         scenario "details view contains POA information" do
           visit "/queue/appeals/#{appeal.uuid}"
-          expect(page).to_not have_content(COPY::CASE_DETAILS_UNRECOGNIZED_POA)
+          expect(page).to have_content(COPY::CASE_DETAILS_UNRECOGNIZED_POA)
```
Comment (jcq) [inline spec/feature/queue/case_details_spec.rb:405]: Just noting that this is a fix for a flake that was acknowledged by Victor team

File: spec/models/serializers/work_queue/power_of_attorney_serializer_spec.rb [hunk 7]
```diff
@@ -0,0 +1,24 @@
+# frozen_string_literal: true
+
+describe WorkQueue::PowerOfAttorneySerializer, :postgres do
+  let(:poa) { create(:bgs_power_of_attorney, poa_participant_id: "10001Dalmations") }
+  subject { described_class.new(poa).serializable_hash[:data][:attributes] }
+
+  describe "#as_json" do
+    context "with an ihp-writing representative organization" do
+      let!(:org) { create(:organization, type: "Vso", participant_id: "10001Dalmations") }
```
Comment (jcq) [inline spec/models/serializers/work_queue/power_of_attorney_serializer_spec.rb:9]: 🐶

**Review by jcq — APPROVED** [review]
Good changes! LGTM once you can connect to clarify why the previous change to `find_by` was there. TY for pushing this through and accommodating our testing difficulties. 😅

**Review by n1zyy — APPROVED** [review]
Hooray! Testing was nice and easy this time around. And 👍 for finding a live bug in the process.

File: app/controllers/claimants_controller.rb (hunk 5 above)
Comment (barshirtcliff) [reply app/controllers/claimants_controller.rb:5]: it wasn't a change to find_by.  it was using ActiveRecord vs using a model-defined find method.  I think it was an oversight that find-by ships with ActiveRecord.  The right thing to do might be to override find_by inside the model and have it both call the ActiveRecord method, and ask BGS.

Comment (barshirtcliff) [reply app/controllers/claimants_controller.rb:5]: good catch on that `no-such-pid` issue, @jcq .  I'm not sure why it thinks that is blank - I will look into it.

Comment (barshirtcliff) [reply app/controllers/claimants_controller.rb:5]:
```

12:42:14 rails.1  | [localhost] [4b76c5b0-19ee-446a-8b13-c74eed982287] [localhost] [COB_USER ] Started PUT "/claimants/no-such-pid/poa" for 127.0.0.1 at 2021-07-09 12:42:14 -0700
12:42:14 rails.1  | [2021-07-09 12:42:14 -0700] Processing by ClaimantsController#refresh_claimant_poa as JSON
12:42:14 rails.1  | [2021-07-09 12:42:14 -0700]   Parameters: {"participant_id"=>"no-such-pid"}
12:42:14 rails.1  | [2021-07-09 12:42:14 -0700]   User Load (2.5ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 71], ["LIMIT", 1]]
12:42:14 rails.1  | [2021-07-09 12:42:14 -0700]    (1.3ms)  BEGIN
12:42:14 rails.1  | [2021-07-09 12:42:14 -0700]    (1.1ms)  COMMIT
12:42:14 rails.1  | [2021-07-09 12:42:14 -0700]   BgsPowerOfAttorney Load (1.9ms)  SELECT  "bgs_power_of_attorneys".* FROM "bgs_power_of_attorneys" WHERE "bgs_power_of_attorneys"."claimant_participant_id" = $1 LIMIT $2  [["claimant_participant_id", "no-such-pid"], ["LIMIT", 1]]
12:42:14 rails.1  | [2021-07-09 12:42:14 -0700]    (1.3ms)  BEGIN
12:42:14 rails.1  | [2021-07-09 12:42:14 -0700]    (1.8ms)  ROLLBACK
12:42:14 rails.1  | [2021-07-09 12:42:14 -0700] Completed 422 Unprocessable Entity in 130ms
```
^ I don't think that's a real possible outcome

File: spec/models/validators/intake_start_validator_spec.rb [hunk 8]
```diff
@@ -21,7 +21,7 @@
     context "when BGS shows a station conflict" do
       let(:station_conflict) { true }
 
-      it "sets error_code \"veteran_not_modifiable\" when BGS shows a station conflict" do
+      it "sets error_code \"veteran_not_modifiable\" when BGS shows a station conflict", skip: "Flake" do
```
Comment (n1zyy) [inline spec/models/validators/intake_start_validator_spec.rb:24]: I'm conflicted here. _In general_, we try not to skip tests unless it's something we introduced/broke, so it'd be better to just re-run the test.

_But_, these are flakes that have existed for a long time and caused lots of frustration, so this feels like something we maybe should have done a long time ago. Do you think it would make sense for us to open a tech-improvement ticket about fixing and re-enabling this test?

**Review by n1zyy — APPROVED** [review]

**Review by n1zyy — APPROVED** [review]

File: spec/models/validators/intake_start_validator_spec.rb (hunk 8 above)
Comment (barshirtcliff) [reply spec/models/validators/intake_start_validator_spec.rb:24]: I'm in favor.  these are confirmed as flakes by foxtrot.  I'll check in with them and see how they'd prefer to see this set up.
