### PR TITLE
Validate queue deep links

### LINKED ISSUE #12367: Fix paginated caching for first response when navigating via a deep link
### What currently happens
When navigating to a paginated queue via a deep link, navigating away from the tab and back sends off a request to the pages api, even though we should have cached this result already.

#### Demo
bug

#### Steps to reproduce
1. Log in as a VLJ support team member (VLJ_SUPPORT_ADMIN)
2. Navigate to http://localhost:3000/organizations/vlj-support?tab=unassigned&page=1
3. Click on the Assigned tab
4. Click back to the Unassigned tab and notice the loading spinner in the queue table

### What we expect to happen
As occurs when not navigating via a deep link, navigating away from a tab and back does not send a request to the pages api.

#### Demo
correct

#### Steps to reproduce
1. Log in as a VLJ support team member (VLJ_SUPPORT_ADMIN)
2. Navigate to http://localhost:3000/organizations/vlj-support
3. Click on the Assigned tab
4. Click back to the Unassigned tab and notice there

## AC
- [ ] Navigating back to a tab that has already been loaded should not trigger a request to the task pages api

### LINKED ISSUE #12400: Disallow queue deep links that do not exist
As brought up in [#12372](https://github.com/department-of-veterans-affairs/caseflow/pull/12372#pullrequestreview-302052309), we should limit deep link parameters to ones that exist. 

### Specifying a higher page number than exists

**Problem**: queue displays no tasks and no way to get to the first page

/organizations/vlj-support?tab=assigned&page=**2**

Screen Shot 2019-10-16 at 8 58 52 AM

### Filtering on a column that does not exist

**Problem**: White screen of death

/organizations/vlj-support?tab=assigned&page=1&filter%5B%5D=col%3D**INVALID_COLUMN_NAME**%26val%3DArnesonColocatedTask

Screen Shot 2019-10-16 at 9 06 54 AM

### Filtering with a value that does not exist

**Problem**: Filter indicator and filter summary indicates a column is being filtered, but no filter values are selected and the results are not filtered

/organizations/vlj-support?tab=assigned&page=1&filter%5B%5D=col%3DtaskColumn%26val%3D**INVALID_FILTER_VALUE**

Screen Shot 2019-10-16 at 9 08 49 AM

### Specifying a tab that does not exist

/organizations/vlj-support?tab=**INVALID_TAB_NAME**

Screen Shot 2019-10-16 at 9 04 13 AM

_Defaults to initial tab_

### Sorting on a column that does not exist

/organizations/vlj-support?tab=assigned&page=1&sort_by=**INVALID_COLUMN**&order=desc

Screen Shot 2019-10-16 at 9 00 43 AM

_Does not sort on any column_

### Sorting with an order that does not exist

/organizations/vlj-support?tab=assigned&page=1&sort_by=taskColumn&order=**INVALID_SORT_ORDER**

Screen Shot 2019-10-16 at 9 01 47 AM

_Defaults to ascending_

### AC
- [ ] Default deep link parameters to
  - [ ] First page of results if the specified page is greater that the total number of pages
  - [ ] Filtering on no columns if the column does not exist of the specified tab
  - [ ] Not filtering on a column if the filter value does not exist
- [ ] After the page loads, the URL should display corrected query params

### Thoughts
 > Not filtering on a column if the filter value does not exist

What if the filter value is valid, but the set of tasks returned (and therefore the filter values passed in queue_config) do not include that value?
We should also only ignore the column and single value that is incorrect. If other columns with valid values are passed, filtering for those should still be displayed. Same goes for other valid values passed with a column with an invalid value.

### PR DESCRIPTION
**Pull request by hschallhorn**
Resolves #12400. Also apparently resolves #12367.

### Description
Validates pagination options passed by the query params of a queue URL.

### Acceptance Criteria
- [ ] Invalid queue query params do not break the rendering of a task table
- [ ] URL after page load is always a correct URL

#### Queue does not break
 - [ ] [Page greater than number of pages of tasks](http://localhost:3000/organizations/vlj-support?tab=assigned&page=2) - Confirm first page of results is shown
 - [ ] [Negative page number](http://localhost:3000/organizations/vlj-support?tab=assigned&page=-11) - Confirm first page of results is shown
 - [ ] [Bad filter column name](http://localhost:3000/organizations/vlj-support?tab=assigned&page=1&filter%5B%5D=col%3DINVALID_COLUMN_NAME%26val%3DArnesonColocatedTask) - Confirm no white screen of death
 - [ ] [Bad filter column value](http://localhost:3000/organizations/vlj-support?tab=assigned&page=1&filter%5B%5D=col%3DtaskColumn%26val%3DINVALID_FILTER_VALUE) - Confirm no filter indicators indicate that a filter is applied
#### URL after page loads is correct
Confirm the invalid URL is replaced with a valid one

 - [ ] [`?tab=INVALID_TAB_NAME`](http://localhost:3000/organizations/vlj-support?tab=INVALID_TAB_NAME)
 `?tab=unassigned&page=1`
 - [ ] [`?tab=assigned&page=2`](http://localhost:3000/organizations/vlj-support?tab=assigned&page=2) 
  `?tab=assigned&page=1`
 - [ ] [`?tab=assigned&page=-12`](http://localhost:3000/organizations/vlj-support?tab=assigned&page=-12) 
  `?tab=assigned&page=1`
- [ ] [`?tab=assigned&page=1&sort_by=INVALID_COLUMN`](http://localhost:3000/organizations/vlj-support?tab=assigned&page=1&sort_by=INVALID_COLUMN) 
  `?tab=assigned&page=1`
- [ ] [`?tab=assigned&page=1&sort_by=taskColumn&order=INVALID_SORT_ORDER`](http://localhost:3000/organizations/vlj-support?tab=assigned&page=1&sort_by=taskColumn&order=INVALID_SORT_ORDER) 
  `?tab=assigned&page=1&sort_by=taskColumn&order=asc`
- [ ] [`?tab=assigned&page=1&filter%5B%5D=col%3DINVALID_COLUMN_NAME%26val%3DAojColocatedTask`](http://localhost:3000/organizations/vlj-support?tab=assigned&page=1&filter%5B%5D=col%3DINVALID_COLUMN_NAME%26val%3DAojColocatedTask) 
  `?tab=assigned&page=1`
- [ ] [`?tab=assigned&page=1&filter%5B%5D=col%3DtaskColumn%26val%3DINVALID_FILTER_VALUE`](http://localhost:3000/organizations/vlj-support?tab=assigned&page=1&filter%5B%5D=col%3DtaskColumn%26val%3DINVALID_FILTER_VALUE) 
  `?tab=assigned&page=1`
- [ ] [`?tab=assigned&page=1&filter%5B%5D=col%3DtaskColumn%26val%3DAojColocatedTask%2CINVALID_FILTER_VALUE`](http://localhost:3000/organizations/vlj-support?tab=assigned&page=1&filter%5B%5D=col%3DtaskColumn%26val%3DAojColocatedTask%2CINVALID_FILTER_VALUE) 
  `?tab=assigned&page=1&filter%5B%5D=col%3DtaskColumn%26val%3DAojColocatedTask`

### CODE REVIEW

File: client/app/queue/components/TaskTable.jsx [hunk 1]
```diff
@@ -197,7 +197,7 @@ export class TaskTableUnconnected extends React.PureComponent {
   }
 
   render = () => <QueueTable
-    columns={this.getQueueColumns}
+    columns={this.getQueueColumns()}
```
Comment (hschallhorn) [inline client/app/queue/components/TaskTable.jsx]: Was returning a function, not an array. Because user queues don't use queue config (yet) we weren't ever seeing this error.

File: client/app/queue/QueueTable.jsx [hunk 2]
```diff
@@ -262,7 +283,11 @@ export default class QueueTable extends React.PureComponent {
         const column = this.props.columns.find((col) => col.name === columnName);
         const values = columnAndValues[1].split('=')[1].split(',');
 
-        filters[column.columnName] = values;
+        if (column) {
```
Comment (hschallhorn) [inline client/app/queue/QueueTable.jsx]: Ensure we don't break when a bad column is specified

File: client/app/queue/QueueTable.jsx [hunk 3]
```diff
@@ -262,7 +283,11 @@ export default class QueueTable extends React.PureComponent {
...
+          const validValues = column.filterOptions.map((filterOption) => filterOption.value);
+
+          filters[column.columnName] = values.filter((value) => validValues.includes(value));
```
Comment (hschallhorn) [inline client/app/queue/QueueTable.jsx]: Ensure we only try to filter by values that exist

File: client/app/queue/QueueTable.jsx [hunk 4]
```diff
@@ -235,6 +232,30 @@ export default class QueueTable extends React.PureComponent {
...
+  validatedPaginationOptions = () => {
+    const { tabPaginationOptions = {}, numberOfPages, columns } = this.props;
+
+    const sortAscending = tabPaginationOptions[QUEUE_CONFIG.SORT_DIRECTION_REQUEST_PARAM] !==
+      QUEUE_CONFIG.COLUMN_SORT_ORDER_DESC;
+    const sortColumn = tabPaginationOptions[QUEUE_CONFIG.SORT_COLUMN_REQUEST_PARAM] || null;
+    const filteredByList = this.getFilters(tabPaginationOptions[`${QUEUE_CONFIG.FILTER_COLUMN_REQUEST_PARAM}[]`]);
+    const pageNumber = (tabPaginationOptions[QUEUE_CONFIG.PAGE_NUMBER_REQUEST_PARAM] - 1) || 0;
+
+    const currentPage = pageNumber + 1 > numberOfPages || pageNumber < 0 ? 0 : pageNumber;
```
Comment (hschallhorn) [inline client/app/queue/QueueTable.jsx]: Ensure we don't try to grab a page of tasks that doesn't exist

File: client/app/queue/QueueTable.jsx [hunk 5]
```diff
@@ -235,6 +232,30 @@ export default class QueueTable extends React.PureComponent {
...
+    const sortColName = columns.map((column) => column.name).includes(sortColumn) ? sortColumn : null;
+
+    // Only request tasks from the back end if we want another page, to sort on a column, or if filters are provided
+    const needsTaskRequest = currentPage || sortColName || !_.isEmpty(filteredByList);
```
Comment (hschallhorn) [inline client/app/queue/QueueTable.jsx]: When a queue is first loaded, the default tasks for each tab are already available to us on the front end. However, with the query parameters, the user could be requesting non default tasks (a new page, only filtered results, sorting on a certain column). If non default parameters are stipulated, we need to show a loading icon and request these tasks from the back end.

File: client/app/queue/QueueTable.jsx (hunk 4 above)
Comment (hschallhorn) [reply client/app/queue/QueueTable.jsx]: Noticed that this also resolves issue #12367 in this sprint.

**Comment by ajspotts** [comment]
Looks good! `validatedPaginationOptions` is rather hefty but totally understand why considering all of the props you had to utilize (not a critique, just an observation) and not to mention you ended up closing another issue with this as well
