### PR TITLE
Abstract v3 api controller

### LINKED ISSUE #11635: Lighthouse API - abstract controller for external api access
We need a controller that consolidates controller features in common with the v3 api work that is exposed to external users through the Lighthouse API gateway.  This should also remove extra brakeman ignore exceptions for new v3 controllers.

### PR DESCRIPTION
**Pull request by erluti**
Resolves #11635

### Description
Adding a controller to be shared between all the new v3 work related to supporting the external proxy access.

### Acceptance Criteria
- [ ] Code compiles correctly

### CODE REVIEW

File: app/controllers/api/external_proxy_controller.rb [hunk 1]
```diff
@@ -0,0 +1,5 @@
+# frozen_string_literal: true
+
+class Api::ExternalProxyController < ActionController::Base
```
Comment (edmangimelli) [inline app/controllers/api/external_proxy_controller.rb]: Just out of curiosity, why the name "Api::ExternalProxyController" and something like "Api::Base"?

Comment (erluti) [reply app/controllers/api/external_proxy_controller.rb]: `ApplicationController` is more of the Rails convention and one already exists in the API namespace.  Since we're not using the name "Lighthouse" in our naming conventions, I figured since this controller was for APIs accessible through the external proxy (aka Kong), I'd call it that.

Comment (pkarman) [reply app/controllers/api/external_proxy_controller.rb]: `ExternalProxyController` is pretty meaningless inside Caseflow.

Why are we not simply inheriting from `Api::ApplicationController`?

Comment (edmangimelli) [reply app/controllers/api/external_proxy_controller.rb]: `Api::V3::BaseController` ?
