### PR TITLE
Fix bugs around bulk assignment UI and write more feature tests

### LINKED ISSUE #11106: Bulk assignment in Hearings Management Team Queue
1. When I try to select tasks by "Address Verification Task", it doesn't give a count of how many to select.

1. The Regional Office should include the state in the drop down.

image

### PR DESCRIPTION
**Pull request by aroltsch**
Resolves #11106 

### Description
Fixes issues around Bulk Assignment modal:

1. If task type is selected, only display regional office list based on the task type selected.
1. Fix blank lines in the dropdown list for user and task type. Note: blank line is allowed in regional office list because it is optional
1. Do not allow to click assign tasks when required fields are missing
1. It appears, the number of tasks is not showing when there are a lot of tasks (more than a hard coded max value)
1. Do not reassign tasks that are already on hold

### CODE REVIEW

File: client/app/queue/components/BulkAssignModal.jsx [hunk 1]
```diff
@@ -141,30 +157,21 @@ class BulkAssignModal extends React.PureComponent {
...
   }
 
   generateRegionalOfficeOptions = () => {
-    const options = _.uniq(this.props.tasks.map((task) => {
+    let filteredTasks = this.filterTasksByTaskType(this.props.tasks);
+
+    const options = _.uniq(filteredTasks.map((task) => {
       return regionalOfficeCity(task);
-    }));
+    })).filter(Boolean);
```
Comment (aroltsch) [inline client/app/queue/components/BulkAssignModal.jsx]: Removes `undefined` from the list

File: client/app/queue/components/BulkAssignModal.jsx [hunk 2]
```diff
@@ -173,28 +180,14 @@ class BulkAssignModal extends React.PureComponent {
       };
     });
 
-    taskOptions.unshift({
```
Comment (aroltsch) [inline client/app/queue/components/BulkAssignModal.jsx]: We don't need a blank line

File: client/app/queue/components/BulkAssignModal.jsx [hunk 3]
```diff
@@ -204,6 +197,12 @@ class BulkAssignModal extends React.PureComponent {
         });
         break;
       }
+      if (filteredTasks.length === issueCounts[i]) { continue; }
+
+      actualOptions.push({
```
Comment (aroltsch) [inline client/app/queue/components/BulkAssignModal.jsx]: Displaying other options for counts

File: client/app/queue/components/BulkAssignModal.jsx [hunk 4]
```diff
@@ -141,30 +157,21 @@ class BulkAssignModal extends React.PureComponent {
       };
     });
 
-    users.unshift({
```
Comment (aroltsch) [inline client/app/queue/components/BulkAssignModal.jsx]: We don't need a blank line.
